### ISSUE TITLE
Pandas also required for installation

### ISSUE THREAD

**Issue by olivertam** [bvaldebenitom/SoloTE#10]
Hi,

This is just minor thing, but I was trying to set up a `conda` environment to run SoloTE, and installed `samtools 1.6`, `bedtools 2.30.0`, `python 3.9.5`, `R-base 4.2.2` and `pysam 0.20.0`. However, it didn't run until I installed `panda 1.5.3`.
Just wanted to let you know to put it in the requirements in case others are trying to install it (with or without `conda`).

Thanks.

**Comment by bvaldebenitom** [comment]
Hi @olivertam!

Thank you for the feedback. I updated the dependency list on the README file.
