### ISSUE TITLE
"dual" option to include reads mapped to coding genes in TE quantification 

### ISSUE THREAD

**Issue by ss6025** [bvaldebenitom/SoloTE#13]
Dear author,

Thanks for making this fantastic tool. I am wondering where and how should I specify the parameter for "dual" option in the following command. No example is specified in the -help page. 

SoloTE_pipeline.py --threads 8 --bam ${BAM_PATH}"/"${bam}"/count/sample_alignments.bam" --teannotation ${TE_BED} --outputprefix ${prefix} --outputdir ${bam} 

Thanks,
Siyu

**Comment by bvaldebenitom** [comment]
Hi @ss6025 !

This option was missing in the latest release. We fixed this for release 1.07, [available here](https://github.com/bvaldebenitom/SoloTE/releases/tag/1.07).

You can activate the "Dual" mode by adding the `--dual` flag to the command. An example using your command is as follows:
`SoloTE_pipeline.py --dual --threads 8 --bam ${BAM_PATH}"/"${bam}"/count/sample_alignments.bam" --teannotation ${TE_BED} --outputprefix ${prefix} --outputdir ${bam}`

You should see the following message if the option is activated:
`Dual mode enabled. SoloTE will calculate TE expression also considering reads annotated to genes.`

Please let me know if you find any issues!

**Comment by ss6025** [comment]
Thank you so much for the update!

On Mon, Apr 10, 2023 at 10:28 AM bvaldebenitom ***@***.***>
wrote:

> Hi @ss6025
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ss6025&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OEFxsYejLcXXsIYPNDdsGA&m=BQ5uHhNKZfceTGE_wnBbM_GiLHaE8Hg2iVFWuIot9ABlRawlllCRrQ7rPG3hLW0g&s=R4ZDE1A-nkDj92E5oESx0NJEWaQ4aYuhhXJA-Cz5dnM&e=>
> !
>
> This option was missing in the latest release. We fixed this for release
> 1.07, available here
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bvaldebenitom_SoloTE_releases_tag_1.07&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OEFxsYejLcXXsIYPNDdsGA&m=BQ5uHhNKZfceTGE_wnBbM_GiLHaE8Hg2iVFWuIot9ABlRawlllCRrQ7rPG3hLW0g&s=Y5rbACmg--I47BrbCccOFA-WGdiOGdgkpHmRJIZ74X8&e=>
> .
>
> You can activate the "Dual" mode by adding the --dual flag to the
> command. An example using your command is as follows:
> SoloTE_pipeline.py --dual --threads 8 --bam
> ${BAM_PATH}"/"${bam}"/count/sample_alignments.bam" --teannotation ${TE_BED}
> --outputprefix ${prefix} --outputdir ${bam}
>
> You should see the following message if the option is activated:
> Dual mode enabled. SoloTE will calculate TE expression also considering
> reads annotated to genes.
>
> Please let me know if you find any issues!
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bvaldebenitom_SoloTE_issues_13-23issuecomment-2D1501886188&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OEFxsYejLcXXsIYPNDdsGA&m=BQ5uHhNKZfceTGE_wnBbM_GiLHaE8Hg2iVFWuIot9ABlRawlllCRrQ7rPG3hLW0g&s=sef3Xi_zXRA8TqSpCWVp6b42NahQZAeHLKqZajn47Mw&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACEMTK2GCAIKCE3NTN3T2KLXAQKKPANCNFSM6AAAAAAWWZE5MU&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OEFxsYejLcXXsIYPNDdsGA&m=BQ5uHhNKZfceTGE_wnBbM_GiLHaE8Hg2iVFWuIot9ABlRawlllCRrQ7rPG3hLW0g&s=aF5FIe4mDklStJNs8OLneXM9LQ_pB7ukF8znEWRc4Kk&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
*Siyu Sun | PhD trained in Gresham Lab
<https://greshamlab.bio.nyu.edu/> (NYU)*
Cell: 917-767-3644
Email: ***@***.***
