### ISSUE TITLE
Re: TE file, score optional

### ISSUE THREAD

**Issue by s2hui** [bvaldebenitom/SoloTE#15]
Hello,

Thank you for this very useful tool which I have just started to use on our single cell data.
I had a question about file format for the TE annotation file.

The documentation says the format should be:

`sequenceName	startPosition	endPosition	sequenceName|startPosition|endPosition|TE_Subfamily:TE_Family:TE_Class|strand	score(optional)	.`

If I don't have a score for the optional score column, do I omit this column entirely as well as the last column (i.e. strand)?  Or should the score column be empty and the last column contain the strand?

Thanks very much for your help,
@s2hui

**Comment by bvaldebenitom** [comment]
Hi @s2hui,

You can omit those columns. There shouldn't be any issue.

Best,
Braulio.

**Comment by s2hui** [comment]
Thanks for clarifying and quick response!
