### ISSUE TITLE
A question about genes + TE x cells

### ISSUE THREAD

**Issue by s2hui** [bvaldebenitom/SoloTE#19]
Hello,
I have a Seurat object with genes x cells created previously from output from CellRanger.  
I finished running soloTE with a TE file with around 7000 TEs on the corresponding bam file and I created a Seurat object with TEs x cells.
Can I call Seurat's merge function to merge these two objects together and then proceed with downstream analyses?
Thanks a lot for clarifying for me.
@s2hui

**Comment by s2hui** [comment]
My apologies, I believe the output from soloTE contains both genes and TEs (i.e. no need to merge).
Please correct me I am mistaken. 
Thanks for your patience!
@s2hui

**Comment by bvaldebenitom** [comment]
Hi @s2hui,

you are correct. The result already contains genes and TEs, so it is not necessary to merge.

Best,
Braulio.

**Comment by s2hui** [comment]
Also the following question came to mind:

I have a number of samples that I have run soloTE on and have created Seurat objects (gene + TE x cells) for each.
I'm interested in running the downstream DE analyses but wonder if I should merge these objects into one big one and then do the DE analysis or do the DE analysis individually.

My samples have corresponding clinical features and I wanted to see if any DE TEs were associated with sample clinical features for example.

I've done different downstream analyses like trajectory and DE analysis on the merged gene x cells Seurat object, so I wonder if I should do likewise.

Thanks kindly for your help in answering all my questions!
@s2hui

**Comment by s2hui** [comment]
Great thanks for your reply!
