### ISSUE TITLE
Cells missing when I compare classical analysis VS SoloTE ?

### ISSUE THREAD

**Issue by wjbsb** [bvaldebenitom/SoloTE#20]
Hi, 

I test your tool on my data and I want to compare classical analysis based on genes VS output from SoloTE.

My classical analysis contains soupX treatment -> filtering -> doublets treatment -> SCTransform -> etc. 
After that, I have a list of "good" barcodes : so, I have 4939 cells.

I check if these barcode are present in output SoloTE after loading in a seurat object. I don't apply any filters. 
The dimension of this seurat object is : 18275 barcodes but the intersect between classical analysis and soloTE output found only 25 barcodes in common.

I don't understand why.

**Comment by bvaldebenitom** [comment]
Hi,

can you share a subset of the BAM file and the results obtained from SoloTE?

**Comment by wjbsb** [comment]
Yes of course...I share that next monday : I down my computer for the weekend...

What are you looking for in the bam? Any tag in particular? 
I launched STARsolo with maximum tags. In particular CB....

**Comment by bvaldebenitom** [comment]
Hi @wjbsb,

Please let me know when you can share the BAM file. 

From the lines you posted, there doesn't seem to be an obvious error. Usually, when comparing with reference barcodes I have seen that there are differences with the "-1" that sometimes appear at the end of the tag, but that doesn't seem to be the case here.
