### ISSUE TITLE
Error with SoloTE_1.08

### ISSUE THREAD

**Issue by kimal999** [bvaldebenitom/SoloTE#21]
Had below error while running "SoloTE_1.08". 

```
Traceback (most recent call last):
  File "SoloTE_1.08/SoloTE_pipeline.py", line 321, in <module>
    marketmatrix_line3 = genenumber.stdout.split(" ")[0]+" "+barcodenumber.stdout.split(" ")[0]+" "+allcounts_number.stdout.split(" ")[0]
AttributeError: 'str' object has no attribute 'stdout'
```
I was able to run the program after changing line 321 to below.

`marketmatrix_line3 = genenumber.split(" ")[0]+" "+barcodenumber.split(" ")[0]+" "+allcounts_number.split(" ")[0]
`

**Comment by bvaldebenitom** [comment]
Hi @kimal999,

thanks for reporting this. It is corrected in the upcoming version.

Best,
Braulio.
