### ISSUE TITLE
pandas error 

### ISSUE THREAD

**Issue by liuyuchenlab** [bvaldebenitom/SoloTE#25]
hi this is my bed file 
![image](https://github.com/bvaldebenitom/SoloTE/assets/131852185/7b505a10-d11e-4e18-8e51-146a49085797)
and this is my bam file
![image](https://github.com/bvaldebenitom/SoloTE/assets/131852185/42e66277-79a5-49f1-8cbb-c5024b4b275a)
they are all chr1,and ERROR: Requested column 3, but database file - only has fields 1 - 0. 

i use this : python /disk5/lyc/biosoft/SoloTE_1.08/SoloTE_pipeline.py  --bam possorted_genome_bam.bam --teannotation /disk5/lyc/reference/mouse/solote.bed  --outputprefix e14 --outputdir /RNA_seq_1/lyc/project/lxm/solote/e14/ -t 1

could you tell me how to fix it?
Thank you

**Comment by bvaldebenitom** [comment]
Hi @liuyuchenlab,

could you share the command line you used to generate the BED file? And the output of `head` on the RepeatMasker file you are using? It doesn't look like the BED file is formatted properly (first column is not chromosome, columns 2 and 3 are not both coordinates, nor column 4 begins with "chr")

**Comment by liuyuchenlab** [comment]
hi，i use this rmsk.txt from UCSC
![image](https://github.com/bvaldebenitom/SoloTE/assets/131852185/d3423b80-017a-4492-87c3-95bc7adb0f17)

**Comment by liuyuchenlab** [comment]
oh is not rmsk is out.gz
