### ISSUE TITLE
Gene Expression Counts in Addition to Transposable Elements in a Count Matrix

### ISSUE THREAD

**Issue by mitra-frn** [bvaldebenitom/SoloTE#27]
Hello,
I have generated a count matrix that currently only includes transposable elements (TEs). However, I would like to expand this matrix to also include gene expression counts. In the related paper, it states that 'After annotating reads associated with TEs, a new matrix is obtained which incorporates both gene and TE expression per cell.' Could you please guide me on how to generate a count matrix that includes both known genes and TEs, as described in the paper?

**Comment by brauliovaldebenitomaturana** [comment]
Hi,

did you check if your BAM file was generated using the following parameters in STAR?:
`--outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM`

Best,
Braulio.

**Comment by bvaldebenitom** [comment]
Hi,

did you check if your BAM file was generated using the following parameters in STAR?:
`--outSAMattributes NH HI nM AS CR UR CB UB GX GN sS sQ sM`

Best,
Braulio.

**Comment by mitra-frn** [comment]
Hi,
You are right.I didn't include the GX GN sS sQ sM attributes in my STAR command.Thank you.
