### ISSUE TITLE
Version package release with License file

### ISSUE THREAD

**Issue by jayramr** [bvaldebenitom/SoloTE#29]
Hello, 

Could you package a new release with the License file. 
I'm preparing bioconda palcage for this SoloTE. For this purpose LICESE file should be included in the packaged file under releases. 

Thanks
Jay

**Comment by jayramr** [comment]
i see the License file in the new release

**Comment by bvaldebenitom** [comment]
Thanks @jayramr. Please let me know how this goes.

**Comment by jayramr** [comment]
I have a question, why we need to excecute the commands with the use of "python SoloTE_pipeline.py" instead of simply calling "SoloTE_pipeline.py" ? 

Because my test getting failling when i called the binary simply as "SoloTE_pipeline.py" . If you can change behaviour of calling the script, will fix the bioconda recipe build. 

https://dev.azure.com/bioconda/25074ded-3133-43ca-af80-895ab87b53cb/_apis/build/builds/41137/logs/26

Thanks
Jay

**Comment by bvaldebenitom** [comment]
Hi @jayramr,

I'm reopening this issue temporarily while I work on solving it.

Thanks for your patience.
