### ISSUE TITLE
soloTE for Smart-Seq2

### ISSUE THREAD

**Issue by gabrielelubatti** [bvaldebenitom/SoloTE#32]
Hello,
Thanks for the nice tool.
I was wondering if there is a way to run soloTE for bam file coming from Smart-Seq2 like protocol ( so one bam file from each cell).
Thanks
Gabriele

**Comment by bvaldebenitom** [comment]
Hi @gabrielelubatti !

Sorry for the delay in replying, but this is one of the features that we are working to bring in for the next release.
