### ISSUE TITLE
running SoloTE on scATAC data

### ISSUE THREAD

**Issue by luisajamaral** [bvaldebenitom/SoloTE#34]
Would it be possible to run SoloTE on scATAC-seq data?

**Comment by bvaldebenitom** [comment]
Hi @luisajamaral !

Thanks for the interest. It is not supported yet, but it is something we are planning to add.

In the meantime, I would recommend to follow an approach similar to that of the work by Pontis et al. (2022) [available here](https://www.nature.com/articles/s41467-022-34800-w). Briefly, you can assess TE enrichment in peaks using BEDtools and the TE annotation file.

Hope this helps,
Braulio.

**Comment by luisajamaral** [comment]
Thanks for the quick response and great tool!
