### ISSUE TITLE
Error running SoloTE v 1.09: FileNotFoundError: [Errno 2] No such file or directory: 'TN_allcounts.txt'

### ISSUE THREAD

**Issue by t1nnenissen** [bvaldebenitom/SoloTE#35]
Hi there, 

I have previously used this amazing tool and you have been a great help. I was really excited to realise the new features in the latest version that allows you to look at global levels of TE expression. 

However, I ran into some difficulties running the new version. Please see below:

<img width="1036" alt="Screenshot 2023-10-04 at 12 33 46" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/588b577c-ecc4-4ddd-abe2-fb496fad0e4f">

Do you have any idea as to what might cause this? 

Best,
Tinne

**Comment by bvaldebenitom** [comment]
Hi @t1nnenissen !

Thank you for the kind words.

Would you mind sharing the output of `samtools view unassigned_alignments_prol.bam|head` and `ls -lht /Users/k20047529/Desktop/soloTE_v1.09/SoloTE_1.09/prol/TN_SoloTE_temp` ?

**Comment by t1nnenissen** [comment]
Hi @bvaldebenitom, 

Thank you so much for getting back on this!

For some reason the command would not run together: 

<img width="1323" alt="Screenshot 2023-10-09 at 09 34 41" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/d1f16e5e-d0bf-4950-80eb-9e191f52f67e">

However, it ran when I split into two: 
<img width="1317" alt="Screenshot 2023-10-09 at 09 35 59" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/8c40ae98-f038-4a63-b9ac-2437b9f0667e">
<img width="1351" alt="Screenshot 2023-10-09 at 09 35 04" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/c5159f86-594d-45cc-87c9-d97b1699e413">

It this hat you were looking for?

**Comment by bvaldebenitom** [comment]
Yes, that's it!

Can you try deleting the temporary folder and running again the pipeline?
`rm -Rf /Users/k20047529/Desktop/soloTE_v1.09/SoloTE_1.09/prol/TN_SoloTE_temp`

`python SoloTE_pipeline.py --threads 10 --bam unassigned_alignments_prol.bam --teannotation hg38_rmsk.bed --outputprefix TN --outputdir prol`

Additionally, please share any messages from this new run. Also, share the output of
`head hg38_rmsk.bed`
`samtools view -L hg38_rmsk.bed -c unassigned_alignments_prol.bam`

**Comment by t1nnenissen** [comment]
After deleting the temporary folder and running the pipeline again I get this error: 

<img width="1352" alt="Screenshot 2023-10-09 at 21 00 56" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/316e1571-e7da-44c8-9ce9-3659026b4e66">

head hg38_rmsk.bed output:
<img width="702" alt="Screenshot 2023-10-09 at 21 01 24" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/3d342993-4af0-4d7b-b9af-4467130a1fe7">

samtools view -L hg38_rmsk.bed -c unassigned_alignments_prol.bam output:
<img width="994" alt="Screenshot 2023-10-09 at 21 01 43" src="https://github.com/bvaldebenitom/SoloTE/assets/117599932/4b54ed98-31cd-4095-8ac1-d6551f43dab6">
