### ISSUE TITLE
Question about output

### ISSUE THREAD

**Issue by mousepixels** [bvaldebenitom/SoloTE#40]
Is there an explanation on the output files/directories:

For example what is a legacytes? Why does the locustes matrix not have any TEs, only genes? Just a general explanation would be beneficial.

Also, I need clarification on the stats output. What exactly does locus-specific mean? Don't the reads map to specific loci, which are then summed to subfamilies? Or does this only mean that no subfamily is represented by only one specific-TE?

TE detected UMIs are distributed as follows:
        Locus-specific TEs: 0 UMIs (0.0%).
        Subfamily TEs: 7594114 (100.0%).

Thank you!!

**Comment by bvaldebenitom** [comment]
Hi @mousepixels,

sorry for the late answer.

There is a graphical description here: https://github.com/bvaldebenitom/SoloTE/issues/30#issuecomment-1721876808

Briefly, Legacy TEs is the standard output of SoloTE which combines locus-specific expression and subfamily expression. Locus-specific expression correspond to reads aligning uniquely to TEs in the genome, which we can unambiguously assess their genomic location. Of the remaining reads, those aligning to more than one location, are counted towards the subfamily level, because we cannot determine their genomic location.

You are probably not getting any locus-specific TE because the BED file probably doesn't contain the keyword "chr". Did you generate the TE BED file using our tool, or did you get it in a different way?

**Comment by weiya428** [comment]
Hello, I'm having the same issue here. In my SoloTE_SoloTE.stats, Locus-specific TEs is 0. How can this be solved?
TE detected UMIs are distributed as follows:
        Locus-specific TEs: 0 UMIs (0.0%).
        Subfamily TEs: 3808562 (100.0%).

Here's my TE's bed file:
Chr1	1133	1421	Chr1|1133|1421|Helitron-N173_OS:Helitron:RC|21|+	21	+
Chr1	1475	1546	Chr1|1475|1546|Helitron-N144_OS:Helitron:RC|16.7|+	16.7	+
Chr1	2229	2296	Chr1|2229|2296|Helitron-N60B_OS:Helitron:RC|18.8|+	18.8	+
Chr1	2260	2314	Chr1|2260|2314|EnSpm-23_OS:CMC-EnSpm:DNA|13.2|-	13.2	-
Chr1	2292	2472	Chr1|2292|2472|Helitron-N188_OS:Helitron:RC|10.1|-	10.1	-

Here's my bam file:
SRR11194114.lite.1.8925686	0	Chr1	3370	255	151M	*	0	0	GATTTCAATCTCCCTTCGTTCCCTGTCCCTAATCCAATACCAATAGGGAGCAATCAGCTGCTCCTCGACGGCGAGGGAGAGGTCGTCGGCCGCGGGCCAAGACAACGGAGATACCGCTGGGGACTACATCAAGTGGATGTGCGGCGCCGGT	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	NH:i:1	HI:i:1	AS:i:147	nM:i:1	RG:Z:run_count_SRR11194114:0:1:unknow_flowcell:0	TX:Z:LOC_Os01g01010.1,+382,151M;LOC_Os01g01010.2,+288,151M	GX:Z:LOC_Os01g01010	GN:Z:LOC_Os01g01010	fx:Z:LOC_Os01g01010	RE:A:E	xf:i:17	CR:Z:TTCTCAATCCGTTGTC	CY:Z:$$$$$$$$$$$$$$$$	CB:Z:TTCTCAATCCGTTGTC-1	UR:Z:GCTTTATACG	UY:Z:$$$$$$$$$$
SRR11194114.lite.1.282381934	0	Chr1	3398	255	151M	*	0	0	CTAATCCAATACCAATAGGGAGCAATCAGCTGCTCCTCGACGGCGAGGGAGATGTCGTCGGCCGCGGGCCAAGACAACGGAGATACCGCTGGGGACTACATCAAGTGGATGTGCGGCGCCGGTGGCCGTGCGGGCGGCGCCATGGCCAACC	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	NH:i:1	HI:i:1	AS:i:149	nM:i:0	RG:Z:run_count_SRR11194114:0:1:unknow_flowcell:0	TX:Z:LOC_Os01g01010.1,+410,151M;LOC_Os01g01010.2,+316,151M	GX:Z:LOC_Os01g01010	GN:Z:LOC_Os01g01010	fx:Z:LOC_Os01g01010	RE:A:E	xf:i:25	CR:Z:CCTTACGCATTGTGCA	CY:Z:????????????????	CB:Z:CCTTACGCATTGTGCA-1	UR:Z:GTGCCTGGGT	UY:Z:??????????	UB:Z:GTGCCTGGGT
SRR11194114.lite.1.343906971	1024	Chr1	3398	255	151M	*	0	0	CTAATCCAATACCAATAGGGAGCAATCAGCTGCTCCTCGACGGCGAGGGAGATGTCGTCGGCCGCGGGCCAAGACAACGGAGATACCGCTGGGGACTACATCAAGTGGATGTGCGGCGCCGGTGGCCGTGCGGGCGGCGCCATGGCCAACC	???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	NH:i:1	HI:i:1	AS:i:149	nM:i:0	RG:Z:run_count_SRR11194114:0:1:unknow_flowcell:0	TX:Z:LOC_Os01g01010.1,+410,151M;LOC_Os01g01010.2,+316,151M	GX:Z:LOC_Os01g01010	GN:Z:LOC_Os01g01010	fx:Z:LOC_Os01g01010	RE:A:E	xf:i:17	CR:Z:CCTTACGCATTGTGCA	CY:Z:????????????????	CB:Z:CCTTACGCATTGTGCA-1	UR:Z:GTGCCTGGGT	UY:Z:??????????	UB:Z:GTGCCTGGGT

Please help me, thank you very much!

**Comment by bvaldebenitom** [comment]
Hi @weiya428,

could you share the output of `ls -lht` on the `temp` directory generated by SoloTE?

**Comment by weiya428** [comment]
Hi, here's a directory of my SoloTE_SoloTE_temp:
-rw-rw-r-- 1 share share 1867976247  7月 16 18:37 SoloTE_allcounts.txt
-rw-rw-r-- 1 share share 1680096038  7月 16 18:43 SoloTE_classtes.txt
-rw-rw-r-- 1 share share   92016401  7月 16 18:35 SoloTE_countpercell_Chr10.counts
-rw-rw-r-- 1 share share   83372446  7月 16 18:35 SoloTE_countpercell_Chr11.counts
-rw-rw-r-- 1 share share   83280513  7月 16 18:35 SoloTE_countpercell_Chr12.counts
-rw-rw-r-- 1 share share  280594981  7月 16 18:37 SoloTE_countpercell_Chr1.counts
-rw-rw-r-- 1 share share  227791691  7月 16 18:34 SoloTE_countpercell_Chr2.counts
-rw-rw-r-- 1 share share  268062991  7月 16 18:36 SoloTE_countpercell_Chr3.counts
-rw-rw-r-- 1 share share  153127127  7月 16 18:30 SoloTE_countpercell_Chr4.counts
-rw-rw-r-- 1 share share  168960425  7月 16 18:31 SoloTE_countpercell_Chr5.counts
-rw-rw-r-- 1 share share  144828527  7月 16 18:30 SoloTE_countpercell_Chr6.counts
-rw-rw-r-- 1 share share  151121670  7月 16 18:32 SoloTE_countpercell_Chr7.counts
-rw-rw-r-- 1 share share  117938805  7月 16 18:28 SoloTE_countpercell_Chr8.counts
-rw-rw-r-- 1 share share   96880670  7月 16 18:33 SoloTE_countpercell_Chr9.counts
-rw-rw-r-- 1 share share 1689166147  7月 16 18:44 SoloTE_familytes.txt
-rw-rw-r-- 1 share share 7891508820  7月 16 18:17 SoloTE_final.bam
-rw-rw-r-- 1 share share    1321960  7月 16 18:21 SoloTE_final.bam.bai
-rw-rw-r-- 1 share share 1867139234  7月 16 18:41 SoloTE_legacytes.txt
-rw-rw-r-- 1 share share 1670631998  7月 16 18:42 SoloTE_locustes.txt
-rw-rw-r-- 1 share share  317013004  7月 16 17:27 SoloTE_nogenes_overlappingtes.bam
-rw-rw-r-- 1 share share     441480  7月 16 17:27 SoloTE_nogenes_overlappingtes.bam.bai
-rw-rw-r-- 1 share share  568861664  7月 16 17:28 SoloTE_nogenes_overlappingtes.bed
-rw-rw-r-- 1 share share    8097996  7月 16 17:28 SoloTE_selectedtes.bed
-rw-rw-r-- 1 share share 1755647214  7月 16 18:46 SoloTE_subfamilytes.txt
-rw-rw-r-- 1 share share  333004621  7月 16 17:36 SoloTE_teannotated.bam
-rw-rw-r-- 1 share share  348500102  7月 16 17:36 temp_annotated_te.bam

**Comment by bvaldebenitom** [comment]
Ok, I see. Thanks! Looks like all files were generated correctly, as they are not empty.

I will add a updated version of SoloTE later. This has to do with "Chr" having the uppercase "C" (currently it expects "chr").

**Comment by weiya428** [comment]
Oh, thank you so much for your help!

**Comment by bvaldebenitom** [comment]
@weiya428 

thanks for your patience. Can you try the attached preliminary version?

Place the file in the same directory as your current SoloTE version, and run it again with the exact same command. It should continue from the matrix generation part, which should be relatively fast.

[SoloTE_pipeline_20240727.tar.gz](https://github.com/user-attachments/files/16400578/SoloTE_pipeline_20240727.tar.gz)
