### ISSUE TITLE
Pipeline failing due to KeyError: 4

### ISSUE THREAD

**Issue by MujeebQadiri** [bvaldebenitom/SoloTE#41]
Hello! First of all, thank you for developing this wonderful tool. I have a question about an error I am receiving which I have pasted below. I ran starSOLO on my fastq files and generated the BED file for dm6 using SoloTE_RepeatMasker_to_Bed.py. I'm going to explore this error myself but would appreciate some help/direction on troubleshooting. Thank you in advance!

On another note I am running this program on a HPC, any general recommendations for memory/time specifications?

**Error Log:**

Traceback (most recent call last):
  File "/home/muq664/.conda/envs/solote/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
ValueError: 4 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Josh/scripts/soloTE/SoloTE_pipeline.py", line 215, in <module>
    tecounts2.loc[tecounts2[4].isnull(),4] = tecounts2.loc[tecounts2[4].isnull(),1]
  File "/home/muq664/.conda/envs/solote/lib/python3.10/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/muq664/.conda/envs/solote/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 4

**Output Log:**
SoloTE started at 15:33:05
[OK] samtools found!
[OK] bedtools found!
SoloTE v1.09 started!
SoloTE Home directory Josh/scripts/soloTE
SoloTE executed from Josh/scripts/soloTE
Results will be stored in Josh/output/CRN00273153
Input BAM file: Josh/data/CRN00273153/Aligned.sortedByCoord.out.bam
Input TE BED file: Josh/scripts/soloTE/dm6_rmsk.bed
Currently working in temporary directory: Josh/output/CRN00273153/CRN00273153_SoloTE_temp
samtools view -@ 15 -O BAM -o CRN00273153_nogenes_overlappingtes.bam -L Josh/scripts/soloTE/dm6_rmsk.bed -e '(exists([CB]) && exists([UB]) && [CB]!="-" && [UB]!="-") && (!exists([GN]) || [GN]=="-")' Josh/data/CRN00273153/Aligned.sortedByCoord.out.bam
samtools index CRN00273153_nogenes_overlappingtes.bam
bedtools bamtobed -i CRN00273153_nogenes_overlappingtes.bam -split > CRN00273153_nogenes_overlappingtes.bed
bedtools intersect -a Josh/scripts/soloTE/dm6_rmsk.bed -b CRN00273153_nogenes_overlappingtes.bed -u > CRN00273153_selectedtes.bed
python Josh/scripts/soloTE/annotateBAM.py CRN00273153_nogenes_overlappingtes.bam CRN00273153_selectedtes.bed temp_annotated_te.bam 1
samtools sort -@ 15 -O BAM -o CRN00273153_teannotated.bam temp_annotated_te.bam
samtools merge --threads 15 -o - Josh/data/CRN00273153/Aligned.sortedByCoord.out.bam CRN00273153_teannotated.bam|samtools view -@ 15 -O BAM -o CRN00273153_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index CRN00273153_final.bam
Counts for chromosome 211000022279188 are being generated in process: 16638
Counts for chromosome Unmapped_Scaffold_8_D1580_D1567 are being generated in process: 16633
Counts for chromosome Unmapped_Scaffold_60_D1601 are being generated in process: 16636
Counts for chromosome Y are being generated in process: 16630
Counts for chromosome 211000022278978 are being generated in process: 16637
Counts for chromosome Unmapped_Scaffold_4_D1555_D1692 are being generated in process: 16635
Counts for chromosome mitochondrion_genome are being generated in process: 16632
Counts for chromosome 4 are being generated in process: 16627
Counts for chromosome 2L are being generated in process: 16622
Counts for chromosome 2R are being generated in process: 16623
Counts for chromosome 3R are being generated in process: 16626
Counts for chromosome 3L are being generated in process: 16625
Counts for chromosome X are being generated in process: 16629

**Comment by MujeebQadiri** [comment]
Further comments:
Running `grep -h SoloTE CRN00273153_allcounts.txt` does not return anything.

The file directory of CRN00273153 looks like the following:
total 5.3G
-rw-rw-r-- 1 muq664 flyrnai 359M Mar 25 17:19 CRN00273153_allcounts.txt
-rw-rw-r-- 1 muq664 flyrnai  680 Mar 25 17:11 CRN00273153_countpercell_211000022278978.counts
-rw-rw-r-- 1 muq664 flyrnai  132 Mar 25 17:11 CRN00273153_countpercell_211000022279188.counts
-rw-rw-r-- 1 muq664 flyrnai  61M Mar 25 17:17 CRN00273153_countpercell_2L.counts
-rw-rw-r-- 1 muq664 flyrnai  73M Mar 25 17:17 CRN00273153_countpercell_2R.counts
-rw-rw-r-- 1 muq664 flyrnai  73M Mar 25 17:18 CRN00273153_countpercell_3L.counts
-rw-rw-r-- 1 muq664 flyrnai  82M Mar 25 17:19 CRN00273153_countpercell_3R.counts
-rw-rw-r-- 1 muq664 flyrnai 7.7M Mar 25 17:12 CRN00273153_countpercell_4.counts
-rw-rw-r-- 1 muq664 flyrnai 870K Mar 25 17:11 CRN00273153_countpercell_mitochondrion_genome.counts
-rw-rw-r-- 1 muq664 flyrnai 6.7K Mar 25 17:11 CRN00273153_countpercell_Unmapped_Scaffold_4_D1555_D1692.counts
-rw-rw-r-- 1 muq664 flyrnai  108 Mar 25 17:11 CRN00273153_countpercell_Unmapped_Scaffold_60_D1601.counts
-rw-rw-r-- 1 muq664 flyrnai 1.9K Mar 25 17:11 CRN00273153_countpercell_Unmapped_Scaffold_8_D1580_D1567.counts
-rw-rw-r-- 1 muq664 flyrnai  63M Mar 25 17:16 CRN00273153_countpercell_X.counts
-rw-rw-r-- 1 muq664 flyrnai  16K Mar 25 17:11 CRN00273153_countpercell_Y.counts
-rw-rw-r-- 1 muq664 flyrnai 4.4G Mar 25 17:10 CRN00273153_final.bam
-rw-rw-r-- 1 muq664 flyrnai 302K Mar 25 17:11 CRN00273153_final.bam.bai
-rw-rw-r-- 1 muq664 flyrnai  19K Mar 25 16:18 CRN00273153_nogenes_overlappingtes.bam
-rw-rw-r-- 1 muq664 flyrnai  15K Mar 25 16:18 CRN00273153_nogenes_overlappingtes.bam.bai
-rw-rw-r-- 1 muq664 flyrnai    0 Mar 25 16:18 CRN00273153_nogenes_overlappingtes.bed
-rw-rw-r-- 1 muq664 flyrnai    0 Mar 25 16:18 CRN00273153_selectedtes.bed
-rw-rw-r-- 1 muq664 flyrnai  20K Mar 25 16:18 CRN00273153_teannotated.bam
-rw-rw-r-- 1 muq664 flyrnai  21K Mar 25 16:18 temp_annotated_te.bam

and running head CRN00273153_allcounts.txt returns:
SteXh:CG42398	AAGACAAAGTCAGAGC	1
SteXh:CG42398	CCCTCTCTCCATTGTT	1
SteXh:CG42398	CCTCCTCGTCTGCCTT	2
SteXh:CG42398	GTAAGTCCAAGGAGTC	1
RR51477	ATTCCCGAGAGGATCC	1
RR51477	CTACATTCATGAGATA	1
RR51477	GGGACCTCAGGTGACA	1
RR51477	GTGGGAACACGAAGAC	3
S{}RR48322	AAACCCAAGTATGCAA	1
S{}RR48322	AACAAAGAGGGCTTCC	1

**Comment by bvaldebenitom** [comment]
Hi @MujeebQadiri !

Thanks for the detailed issue report.

Based on the information provided, it looks like no TEs are found at the beginning of the analysis (`CRN00273153_selectedtes.bed` is empty). This usually is an issue of either
1. A mismatch between chromosome naming in the BAM file and the BED file.
2. Lack of CB and UB tags in the BAM file.

Could you kindly provide the output of the following commands?
```
samtools view Josh/data/CRN00273153/Aligned.sortedByCoord.out.bam|head
head Josh/scripts/soloTE/dm6_rmsk.bed
```

**Comment by ferygood** [comment]
Hello, 
Thank you for developing SoloTE, it is a really exciting tool.
I have also encountered this KeyError: 4 issue, and here is the log file:
 
```Wed Apr 10 13:25:40 CEST 2024
cmp249
[bam_sort_core] merging from 0 files and 5 in-memory blocks...
SoloTE started at 13:25:44
[OK] samtools found!
[OK] bedtools found!
SoloTE v1.09 started!
SoloTE Home directory /data/scratch/yaochung41/SoloTE
SoloTE executed from /data/scratch/yaochung41/SoloTE
Results will be stored in /data/scratch/yaochung41/SoloTE/baiOut
Input BAM file: /data/scratch/yaochung41/SoloTE/breastCancerData/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam
Input TE BED file: /data/scratch/yaochung41/SoloTE/hg38_rmsk.bed
Currently working in temporary directory: /data/scratch/yaochung41/SoloTE/baiOut/bc_SoloTE_temp
samtools view -@ 5 -O BAM -o bc_nogenes_overlappingtes.bam -L /data/scratch/yaochung41/SoloTE/hg38_rmsk.bed -e '(exists([CB]) && exists([UB]) && [CB]!="-" && [UB]!="-") && (!exists([GN]) || [GN]=="-")' /data/scratch/yaochung41/SoloTE/breastCancerData/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam
samtools index bc_nogenes_overlappingtes.bam
bedtools bamtobed -i bc_nogenes_overlappingtes.bam -split > bc_nogenes_overlappingtes.bed
bedtools intersect -a /data/scratch/yaochung41/SoloTE/hg38_rmsk.bed -b bc_nogenes_overlappingtes.bed -u > bc_selectedtes.bed
python /data/scratch/yaochung41/SoloTE/annotateBAM.py bc_nogenes_overlappingtes.bam bc_selectedtes.bed temp_annotated_te.bam 1
samtools sort -@ 5 -O BAM -o bc_teannotated.bam temp_annotated_te.bam
samtools merge --threads 5 -o - /data/scratch/yaochung41/SoloTE/breastCancerData/CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam bc_teannotated.bam|samtools view -@ 5 -O BAM -o bc_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index bc_final.bam
Counts for chromosome chr12 are being generated in process: 2139498
Counts for chromosome chr17 are being generated in process: 2139498
Counts for chromosome chr21 are being generated in process: 2139498
Counts for chromosome chr22 are being generated in process: 2139498
Counts for chromosome chr3 are being generated in process: 2139498
Counts for chromosome chrM are being generated in process: 2139498
Counts for chromosome chr10 are being generated in process: 2139496
Counts for chromosome chr15 are being generated in process: 2139496
Counts for chromosome chr18 are being generated in process: 2139496
Counts for chromosome chr19 are being generated in process: 2139496
Counts for chromosome chr7 are being generated in process: 2139496
Counts for chromosome chr1 are being generated in process: 2139495
Counts for chromosome chr5 are being generated in process: 2139495
Counts for chromosome chr8 are being generated in process: 2139495
Counts for chromosome chrY are being generated in process: 2139495
Counts for chromosome KI270728.1 are being generated in process: 2139495
Counts for chromosome KI270727.1 are being generated in process: 2139495
Counts for chromosome KI270729.1 are being generated in process: 2139495
Counts for chromosome KI270743.1 are being generated in process: 2139495
Counts for chromosome GL000205.2 are being generated in process: 2139495
Counts for chromosome KI270733.1 are being generated in process: 2139495
Counts for chromosome GL000224.1 are being generated in process: 2139495
Counts for chromosome GL000216.2 are being generated in process: 2139495
Counts for chromosome KI270725.1 are being generated in process: 2139495
Counts for chromosome KI270744.1 are being generated in process: 2139495
Counts for chromosome KI270734.1 are being generated in process: 2139495
Counts for chromosome GL000213.1 are being generated in process: 2139495
Counts for chromosome KI270751.1 are being generated in process: 2139495
Counts for chromosome KI270730.1 are being generated in process: 2139495
Counts for chromosome KI270711.1 are being generated in process: 2139495
Counts for chromosome KI270752.1 are being generated in process: 2139495
Counts for chromosome chr13 are being generated in process: 2139499
Counts for chromosome chr14 are being generated in process: 2139499
Counts for chromosome chr16 are being generated in process: 2139499
Counts for chromosome chr20 are being generated in process: 2139499
Counts for chromosome chr4 are being generated in process: 2139499
Counts for chromosome chr9 are being generated in process: 2139499
Counts for chromosome chrX are being generated in process: 2139499
Counts for chromosome chr11 are being generated in process: 2139497
Counts for chromosome chr2 are being generated in process: 2139497
Counts for chromosome chr6 are being generated in process: 2139497
Traceback (most recent call last):
  File "/home/yaochung41/anaconda3/envs/soloTE/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
ValueError: 4 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/scratch/yaochung41/SoloTE/SoloTE_pipeline.py", line 217, in <module>
    tecounts2.loc[tecounts2[4].isnull(),4] = tecounts2.loc[tecounts2[4].isnull(),1]
  File "/home/yaochung41/anaconda3/envs/soloTE/lib/python3.10/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/yaochung41/anaconda3/envs/soloTE/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 4
```

1. I followed the instruction using `SoloTE_RepeatMasker_to_BED.py` to create `hg38_rmsk.bed` and run the pipeline.
2. Here are the first few lines of my BED file and BAM file:
```
head -n 3 hg38_rmsk.bed
chr1	11505	11675	chr1|11505|11675|L1MC5a:L1:LINE|25.1|-	25.1	-
chr1	11678	11780	chr1|11678|11780|MER5B:hAT-Charlie:DNA|29.4|-	29.4	-
chr1	15265	15355	chr1|15265|15355|MIR3:MIR:SINE|23.0|-	23.0	-
```

```
samtools view CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam | head -n 3
A00836:1179:HNNN7DSX3:1:2347:7301:2801	1040	chr1	69486	255	50M	*	0	0	CGCATGTGTCGGCATTATGGCTGTCACATGGGGAATTGGCTTTCTCCATT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0	RG:Z:CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma:0:1:HNNN7DSX3:1	GX:Z:ENSG00000186092	GN:Z:OR4F5	fx:Z:ENSG00000186092	pr:Z:ENSG00000186092|OR4F5|118842c	RE:A:E	xf:i:17	CR:Z:TCCGTGCCAACTCGAG	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:TCCGTGCCAACTCGAG-1UR:Z:GTCTACTCCTGG	UY:Z:FFFFFFFFFFFF	UB:Z:GTCTACTCCTGG
A00836:1179:HNNN7DSX3:1:2225:23077:32127	1040	chr1	69486	255	50M	*	0	0	CGCATGTGTCGGCATTATGGCTGTCACATGGGGAATTGGCTTTCTCCATT	FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0RG:Z:CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma:0:1:HNNN7DSX3:1	GX:Z:ENSG00000186092	GN:Z:OR4F5	fx:Z:ENSG00000186092	pr:Z:ENSG00000186092|OR4F5|118842c	RE:A:E	xf:i:17	CR:Z:ACGATGTTGGTGTAAG	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:ACGATGTTGGTGTAAG-1UR:Z:TGCAAACTAAAA	UY:Z:FFFFFFFFFFFF	UB:Z:TGCAAACTAAAA
A00836:1179:HNNN7DSX3:1:1564:18358:30405	16	chr1	69486	255	50M	*	0	0	CGCATGTGTCGGCATTATGGCTGTCACATGGGGAATTGGCTTTCTCCATT	FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:49	nM:i:0RG:Z:CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma:0:1:HNNN7DSX3:1	GX:Z:ENSG00000186092	GN:Z:OR4F5	fx:Z:ENSG00000186092	pr:Z:ENSG00000186092|OR4F5|118842c	RE:A:E	xf:i:25	CR:Z:GATCAAGATTCTAATA	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:GATCAAGATTCTAATA-1UR:Z:ATCACATCCGGA	UY:Z:FFFFFFFFFFFF	UB:Z:ATCACATCCGGA

```

3. Below is the temporal files inside the output folder
```
ls -lht
total 8.1G
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 1.1G Apr 10 14:48 bc_allcounts.txt
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  33M Apr 10 14:48 bc_countpercell_chrX.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  57M Apr 10 14:47 bc_countpercell_chr7.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 2.4M Apr 10 14:47 bc_countpercell_chrM.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  60M Apr 10 14:47 bc_countpercell_chr6.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   52 Apr 10 14:45 bc_countpercell_KI270752.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   35 Apr 10 14:45 bc_countpercell_KI270711.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   26 Apr 10 14:45 bc_countpercell_KI270730.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   28 Apr 10 14:45 bc_countpercell_KI270751.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 6.2K Apr 10 14:45 bc_countpercell_GL000213.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 2.8K Apr 10 14:45 bc_countpercell_KI270734.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  70K Apr 10 14:45 bc_countpercell_KI270744.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   87 Apr 10 14:45 bc_countpercell_KI270725.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   27 Apr 10 14:45 bc_countpercell_GL000216.2.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  168 Apr 10 14:45 bc_countpercell_GL000224.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   27 Apr 10 14:45 bc_countpercell_KI270733.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  33K Apr 10 14:45 bc_countpercell_GL000205.2.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   27 Apr 10 14:45 bc_countpercell_KI270743.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick   87 Apr 10 14:45 bc_countpercell_KI270729.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 3.9K Apr 10 14:45 bc_countpercell_KI270727.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  12K Apr 10 14:45 bc_countpercell_KI270728.1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  12K Apr 10 14:45 bc_countpercell_chrY.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  36M Apr 10 14:45 bc_countpercell_chr8.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  40M Apr 10 14:45 bc_countpercell_chr9.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  61M Apr 10 14:44 bc_countpercell_chr3.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  40M Apr 10 14:42 bc_countpercell_chr4.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  42M Apr 10 14:42 bc_countpercell_chr5.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  80M Apr 10 14:42 bc_countpercell_chr19.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  77M Apr 10 14:41 bc_countpercell_chr2.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 124M Apr 10 14:39 bc_countpercell_chr1.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  38M Apr 10 14:39 bc_countpercell_chr20.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  25M Apr 10 14:39 bc_countpercell_chr22.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  11M Apr 10 14:37 bc_countpercell_chr21.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  65M Apr 10 14:36 bc_countpercell_chr17.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  44M Apr 10 14:34 bc_countpercell_chr16.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  68M Apr 10 14:33 bc_countpercell_chr11.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  15M Apr 10 14:32 bc_countpercell_chr18.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  29M Apr 10 14:31 bc_countpercell_chr15.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  57M Apr 10 14:31 bc_countpercell_chr12.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  35M Apr 10 14:31 bc_countpercell_chr14.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  40M Apr 10 14:29 bc_countpercell_chr10.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  18M Apr 10 14:28 bc_countpercell_chr13.counts
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 2.3M Apr 10 14:26 bc_final.bam.bai
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 5.9G Apr 10 14:25 bc_final.bam
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 746K Apr 10 13:53 bc_teannotated.bam
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 749K Apr 10 13:53 temp_annotated_te.bam
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 370K Apr 10 13:53 bc_selectedtes.bed
-rw-r--r-- 1 yaochung41 bcp_ag-nowick  21M Apr 10 13:53 bc_nogenes_overlappingtes.bed
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 1.7M Apr 10 13:53 bc_nogenes_overlappingtes.bam.bai
-rw-r--r-- 1 yaochung41 bcp_ag-nowick 8.2M Apr 10 13:53 bc_nogenes_overlappingtes.bam
```

Could you provide some ideas to handle this issue? 
Thank you very much for your time and help!

Best,
Yao

**Comment by bvaldebenitom** [comment]
Hi @ferygood,

thanks for the detailed report.  

It seems that there is a match between the BED and the BAM file in terms of chromosome identifiers. Looking at the file list, it seems likely that not many TEs are being detected.

Could you attach the files `bc_teannotated.bam` and `bc_selectedtes.bed` here?

**Comment by ferygood** [comment]
Hello @bvaldebenitom ,

Thank you for your fast response. 
Sure, no problem. 
I show you the first three lines from the files. You can also find the full content here: [bc_files.zip](https://github.com/bvaldebenitom/SoloTE/files/14957377/bc_files.zip)
bc_teannotated.bam
```
A00836:1179:HNNN7DSX3:1:1623:9426:19914	16	chr1	1051748	0	39M68201N11M	*	0	0	GGGGACGTGGATACCTTGCCCATTGACGGGCGGACCTTTGACGCGCCCCT	:FFF::FF::FF,FFF,,,FF,,F,,F,::,F:FFF,:,:,F,F,,,FFF	NH:i:2	HI:i:1	AS:i:38	nM:i:4	RG:Z:CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma:0:1:HNNN7DSX3:1	xf:i:0	CR:Z:GGCTGGACGCTCTAAT	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:GGCTGGACGCTCTAAT-1	UR:Z:AGCACTAGATGT	UY:Z:FFFFFFFFF:FFUB:Z:AGCACTAGATGT	GX:Z:chr1|1119751|1120058|AluSz:Alu:SINE|9.7|+	GN:Z:SoloTE|AluSz:Alu:SINE
A00836:1179:HNNN7DSX3:1:1356:15754:15687	16	chr1	1443668	0	9S41M	*	0	0	TATATCGGGGGTCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT	,,,,,,,,FF,,,F,,::F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:40	nM:i:0	RG:Z:CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma:0:1:HNNN7DSX3:1	xf:i:0	CR:Z:GGCAATACCTTCAGAA	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:GGCAATACCTTCAGAA-1	UR:Z:GCGGGACCCTGA	UY:Z:FFFFFFFFFFFFUB:Z:GCGGGACCCTGA	GX:Z:chr1|1443397|1443671|AluSx1:Alu:SINE|11.3|-	GN:Z:SoloTE|AluSx1:Alu:SINE
A00836:1179:HNNN7DSX3:1:1356:15754:15687	16	chr1	1443668	0	9S41M	*	0	0	TATATCGGGGGTCCCTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT	,,,,,,,,FF,,,F,,::F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	AS:i:40	nM:i:0	RG:Z:CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma:0:1:HNNN7DSX3:1	xf:i:0	CR:Z:GGCAATACCTTCAGAA	CY:Z:FFFFFFFFFFFFFFFF	CB:Z:GGCAATACCTTCAGAA-1	UR:Z:GCGGGACCCTGA	UY:Z:FFFFFFFFFFFFUB:Z:GCGGGACCCTGA	GX:Z:chr1|1443674|1443998|AluJb:Alu:SINE|17.0|-	GN:Z:SoloTE|AluJb:Alu:SINE
```

bc_selectedtes.bed
```
chr1	1119751	1120058	chr1|1119751|1120058|AluSz:Alu:SINE|9.7|+	9.7	+
chr1	1443397	1443671	chr1|1443397|1443671|AluSx1:Alu:SINE|11.3|-	11.3	-
chr1	1443674	1443998	chr1|1443674|1443998|AluJb:Alu:SINE|17.0|-	17.0	-
```

Thanks a lot!

**Comment by bvaldebenitom** [comment]
Hi @ferygood,

thank you for your patience. Can you try the v1.10? It is available [here](https://github.com/bvaldebenitom/SoloTE/blob/main/SoloTE_pipeline.py) (you can just replace the previous version with this file).

Basically, this long-standing error seems to occur when no locus-specific TEs are detected. Can you check whether you have MAPQs equal to 255 with:
`samtools view --min-MQ 255 -c CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam`+

Also, can you share the output of 
`samtools view CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam|awk '{print $5}'|sort|uniq -c`
Depending on how the reads were aligned, it is likely that the MAPQ distribution is different than expected.

The new v1.10 should run to completion. However, I find it strange to not have any locus-specific TEs. This is based on my experience, but it is likely that indeed many young copies are being expressed in your data.

**Comment by MujeebQadiri** [comment]
> Hi @MujeebQadiri !
> 
> Thanks for the detailed issue report.
> 
> Based on the information provided, it looks like no TEs are found at the beginning of the analysis (`CRN00273153_selectedtes.bed` is empty). This usually is an issue of either
> 
> 1. A mismatch between chromosome naming in the BAM file and the BED file.
> 2. Lack of CB and UB tags in the BAM file.
> 
> Could you kindly provide the output of the following commands?
> 
> ```
> samtools view Josh/data/CRN00273153/Aligned.sortedByCoord.out.bam|head
> head Josh/scripts/soloTE/dm6_rmsk.bed
> ```
> 
> As for HPC recommendations, you can use as starting point about a third to a half of the amount of RAM used during the alignment step with STAR, and ~1 hour per each 10 Gb the size of the BAM file (i.e., I have needed about 10-12 hours for a >100 Gb BAM file with 30 Gb requested for memory).

Hello,

I appreciate your responsiveness to ferygood's and my errors. I followed the following recommendations from the post linked below and removed the "chr" in the first column of the BED file. It worked perfectly, thank you!

https://github.com/bvaldebenitom/SoloTE/issues/37#issuecomment-1838909529

**Comment by ferygood** [comment]
Hello @bvaldebenitom,

## run v1.10

Thank you for providing the v1.10 of SoloTE. It run without errors now, and as you mentioned there are no Locus-specific TEs in detected UMIs:

The result log files:
```
A total of 147236684 UMIs are in the final matrix.
Of these,
	147227973 (99.994%) correspond to genes.
	and 8711 (0.006%) correspond to TEs.
TE detected UMIs are distributed as follows:
	Locus-specific TEs: 0 UMIs (0.0%).
	Subfamily TEs: 8711 (100.0%).

```
Do you mean that young copies would not be detected in locus-specific category?

## samtools view

Here is the output of running samtools
```
samtools view --min-MQ 255 -c CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam
212013378
```

```
samtools view CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam|awk '{print $5}'|sort|uniq -c
2577953 0
 462235 1
212013378 255
 459872 3
```

I also think it is a bit strange to have no locus-specific TEs, and I am thinking about remapping the reads with STAR using different parameters. I will also update here if I have any new findings.

If you have any thoughts or feedback, I would be really happy to hear about it.
Thank you!

**Comment by bvaldebenitom** [comment]
Thanks @MujeebQadiri for confirming the solution!

@ferygood , there is a chance that some reads can still be allocated uniquely to young copies (again, this is based on my personal experience), but that's likely an explanation for what you are seeing.

Another explanation is, as you correctly point out, related to the alignment process, and remapping with STAR setting the following options can help:
```
--winAnchorMultimapNmax 100
--outFilterMultimapNmax 100
--outSAMmultNmax 1
```

Is your data from CellRanger or a similar 10X Genomics tool? I'm aware that on their latest versions they also count intronic reads towards genes, and this would interfere with the potential of reads being allocated to TEs.

You can check the output of the following commands to see if that could also be an issue:
`samtools view --min-MQ 255 -L /data/scratch/yaochung41/SoloTE/hg38_rmsk.bed -e '(exists([CB]) && exists([UB]) && [CB]!="-" && [UB]!="-") -c CytAssist_11mm_FFPE_Human_Ovarian_Carcinoma_possorted_genome_bam.bam`

This would give the number of reads overlapping with TEs that have a proper CB and UB tag, regardless of whether they are already assigned to genes. If the command outputs a number greater than 0, you can also remove `--min-MQ 255` to see how the number would change by considering reads regardless of MAPQ.

Finally, another idea I can think of: did you check whether the genome version used for the BAM file is the same as the BED file? They would "match" (i.e., "chr1" appears in both as such), but the coordinates of different features, including TEs, could vary.
