### ISSUE TITLE
Parameters for generating inputs for SoloTE

### ISSUE THREAD

**Issue by hgiles5** [bvaldebenitom/SoloTE#44]
Hi, 

Thanks for all your work generating SoloTE. I'm wondering about some specifics for generating the input bam file. Could you post an example of the parameters you used with STAR to generate the bam files prior to analysis with SoloTE? In addition to the three parameters for multimapping you mentioned in the paper, do you recommend using STARsolo? I'm asking in the context of scRNAseq or GEX reads from scMultiome with data generated on the 10X platform.

Thank you!

**Comment by bvaldebenitom** [comment]
Hi @hgiles5 !

Thanks for the kind words.

Here are the recommended options to use in STAR:
```
--outSAMattributes NH HI nM AS CR UR CY UY CB UB GX GN sS sQ sM
 --winAnchorMultimapNmax 100
--outFilterMultimapNmax 100
--outSAMmultNmax 1
```

Yes, I recommend using STARsolo, in particular considering that [recent versions of CellRanger](https://kb.10xgenomics.com/hc/en-us/articles/4998749959949-I-do-not-want-to-include-intronic-reads-in-my-analysis-Can-I-do-that-in-Cell-Ranger) by default assign intronic reads to genes, and they can often be associated with TEs.

I haven't tested SoloTE with scMultiome data. By any chance are you re-analyzing public data? If so, you can send me the accession or link to it so I can test the pipeline. I will verify too if there are public multiome datasets in the 10X website.

**Comment by hgiles5** [comment]
Thanks. Could you provide an example of an entire STAR command you would use? Unfortunately I can't share my dataset, but there is a public scMultiome PBMC dataset from 10X [](https://support.10xgenomics.com/single-cell-multiome-atac-gex/datasets/1.0.0/pbmc_granulocyte_sorted_10k )

**Comment by hgiles5** [comment]
An alignment from the fastq files

**Comment by bvaldebenitom** [comment]
This is how the entire command would look:

```
STAR
 --outSAMattributes NH HI nM AS CR UR CY UY CB UB GX GN sS sQ sM
 --outSAMtype BAM SortedByCoordinate
 --outFilterMultimapNmax 100
 --winAnchorMultimapNmax 100
 --outMultimapperOrder Random
 --outSAMmultNmax 1
 --runRNGseed 777
 --runThreadN 21
 --soloType CB_UMI_Simple
 --soloCBwhitelist BARCODES_WHITELIST
 --readFilesIn FASTQ2 FASTQ1
 --genomeDir STAR_GENOMEDIR
```
You need to modify `BARCODES_WHITELIST`, `FASTQ2 FASTQ1` and `STAR_GENOMEDIR` accordingly. Hope this helps!
