### ISSUE TITLE
Failed to download reference

### ISSUE THREAD

**Issue by WG20231** [bvaldebenitom/SoloTE#45]
Hi,

When I was downloading the hg38 using python SoloTE_RepeatMasker_to_BED.py -g hg38, I got below error:

requests.exceptions.SSLError: HTTPSConnectionPool(host='hgdownload.soe.ucsc.edu', port=443): Max retries exceeded with url: /goldenPath/hg38/bigZips/hg38.fa.out.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))

Could you help me fix this? Thank you.

**Comment by bvaldebenitom** [comment]
Hi @WG20231,

I just tested the script and works ok. Could you try again? By any chance are you running this on an HPC that might require further proxy settings to allow for external file download?
