### ISSUE TITLE
Running SoloTE on BAM files

### ISSUE THREAD

**Issue by singhbhavya** [bvaldebenitom/SoloTE#49]
Hi there! I am planning to run SoloTE on publicly available data (HTAN). I can either download raw FASTQ files and align them to the genome myself, or use the pre-aligned BAMs provided by HTAN. I wanted to ask whether it is okay to use BAMs that were outputted using the default `cellranger count` function (as is the case for all BAMs provided by HTAN), or if the BAMs need to be generated with specific STAR parameters (ex: --outFilterMultimapNmax). If the latter is the case, are there specific alignment parameters you recommend before running SoloTE? Thank you so much!

**Comment by bvaldebenitom** [comment]
Hi @singhbhavya 

thanks for the message.

I think it's ok to use CellRanger BAM files if you are sure that they do not contain more than one alignment per multimapping read. I noticed that they might include them and you might need to filter with this:
`samtools view -F 256 -O BAM -o newbamfilename inputbamfilename`

However, using the aforementioned method resulted in less total number of reads than when re-mapping using STAR and applying more sensitive parameters. The following is the full STAR command I would recommend to generate the best inputs for SoloTE, using FASTQ as inputs:

```
STAR
 --outSAMattributes NH HI nM AS CR UR CY UY CB UB GX GN sS sQ sM
 --outSAMtype BAM SortedByCoordinate
 --outFilterMultimapNmax 100
 --winAnchorMultimapNmax 100
 --outMultimapperOrder Random
 --outSAMmultNmax 1
 --runRNGseed 777
 --runThreadN 21
 --soloType CB_UMI_Simple
 --soloCBwhitelist BARCODES_WHITELIST
 --readFilesIn FASTQ2 FASTQ1
 --genomeDir STAR_GENOMEDIR
```

Please let me know if this helps!

**Comment by singhbhavya** [comment]
Hi, @bvaldebenitom! Thank you so much for your help. I've decided to download and use the raw FASTQ files, and will run STARsolo as outlined above.  Hopefully, all will go well & I'll be able to run SoloTE! Thank you so much again!

**Comment by singhbhavya** [comment]
Apologies, just one more question - what do you think about using `--soloMultiMappers EM`?

**Comment by singhbhavya** [comment]
Hi there! I am having some errors while running SoloTE. The error is similar to this GitHub issue #41 , where there is a "KeyError 4". Here is my report:

This is how I ran STARsolo. It includes the parameters you previously advised on, as well as a few extra parameters to ensure that the output data looks similar to CellRanger 3.x.x. 

```
STAR --outSAMattributes NH HI nM AS CR UR CY UY CB UB GX GN sS sQ sM\
    --outSAMtype BAM SortedByCoordinate\
    --outFilterMultimapNmax 100\
    --winAnchorMultimapNmax 100\
    --outMultimapperOrder Random\
    --outSAMmultNmax 1\
    --runRNGseed 777\
    --runThreadN 1\
    --soloUMIlen 12\
    --soloType CB_UMI_Simple\
    --soloCBwhitelist databases/remotefiles/3M-february-2018.txt\
    --soloCellFilter EmptyDrops_CR\
    --soloCBmatchWLtype 1MM_multi_Nbase_pseudocounts\
    --soloUMIfiltering MultiGeneUMI_CR\
    --soloUMIdedup 1MM_CR\
    --soloMultiMappers EM\
    --readFilesCommand zcat\
    --readFilesIn /sc/arion/projects/Perturb-map/scRNAseq/scRNAseq_PDAC/Zhou_NatGenetics/Zhou_NatGen_scRNAseq_raw/TWCE-HT242P1-XBMN1_1_S3_L004_R2_001.fastq.gz /sc/arion/projects/Perturb-map/scRNAseq/scRNAseq_PDAC/Zhou_NatGenetics/Zhou_NatGen_scRNAseq_raw/TWCE-HT242P1-XBMN1_1_S3_L004_R1_001.fastq.gz\
    --genomeDir databases/indexes/STAR_GRCh38\
    --outFileNamePrefix results/starsolo_algn/HTA12_25_3/HTA12_25_3_GDC38.
```

This is how I ran SoloTE:

```
python /sc/arion/projects/Perturb-map/scRNAseq/scRNAseq_PDAC/Zhou_NatGenetics/sctequant/packages/SoloTE/SoloTE_pipeline.py --threads 8 --bam results/starsolo_algn/HTA12_25_3/HTA12_25_3_GDC38.Aligned.sortedByCoord.out.bam --teannotation databases/annotations/hg38_rmsk.bed --outputprefix HTA12_25_3 --outputdir results/SoloTE/HTA12_25_
```

This is my error:

```
samtools merge --threads 8 -o - /sc/arion/projects/Perturb-map/scRNAseq/scRNAseq_PDAC/Zhou_NatGenetics/sctequant/results/starsolo_algn/HTA12_25_3/HTA12_25_3_GDC38.Aligned.sortedByCoord.out.bam HTA12_25_3_teannotated.bam|samtools view -@ 8 -O BAM -o HTA12_25_3_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index HTA12_25_3_final.bam
Counts for chromosome 1 are being generated in process: 75547
Counts for chromosome 10 are being generated in process: 75548
Counts for chromosome 11 are being generated in process: 75549
Counts for chromosome 12 are being generated in process: 75550
Counts for chromosome 13 are being generated in process: 75551
Counts for chromosome 14 are being generated in process: 75552
Counts for chromosome 15 are being generated in process: 75553
Counts for chromosome 16 are being generated in process: 75554
Counts for chromosome 17 are being generated in process: 75551
Counts for chromosome 18 are being generated in process: 75554
Counts for chromosome 19 are being generated in process: 75552
Counts for chromosome 2 are being generated in process: 75548
Counts for chromosome 20 are being generated in process: 75553
Counts for chromosome 21 are being generated in process: 75554
Counts for chromosome 22 are being generated in process: 75550
Counts for chromosome 3 are being generated in process: 75554
Counts for chromosome 4 are being generated in process: 75553
Counts for chromosome 5 are being generated in process: 75550
Counts for chromosome 6 are being generated in process: 75551
Counts for chromosome 7 are being generated in process: 75553
Counts for chromosome 8 are being generated in process: 75547
Counts for chromosome 9 are being generated in process: 75552
Counts for chromosome MT are being generated in process: 75550
Counts for chromosome X are being generated in process: 75554
Counts for chromosome Y are being generated in process: 75548
Counts for chromosome KI270727.1 are being generated in process: 75548
Counts for chromosome GL000195.1 are being generated in process: 75548
Counts for chromosome KI270734.1 are being generated in process: 75548
Counts for chromosome GL000218.1 are being generated in process: 75548
Counts for chromosome KI270711.1 are being generated in process: 75547
Traceback (most recent call last):
  File "/sc/arion/work/singhb22/test-env/envs/SoloTE/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/sc/arion/projects/Perturb-map/scRNAseq/scRNAseq_PDAC/Zhou_NatGenetics/sctequant/packages/SoloTE/SoloTE_pipeline.py", line 226, in <module>
    tecounts2.loc[tecounts2[4].isnull(),4] = tecounts2.loc[tecounts2[4].isnull(),1]
  File "/sc/arion/work/singhb22/test-env/envs/SoloTE/lib/python3.9/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/sc/arion/work/singhb22/test-env/envs/SoloTE/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 4
```

This is the top 3 lines of my BED file:

```
chr1	11505	11675	chr1|11505|11675|L1MC5a:L1:LINE|25.1|-	25.1	-
chr1	11678	11780	chr1|11678|11780|MER5B:hAT-Charlie:DNA|29.4|-	29.4	-
chr1	15265	15355	chr1|15265|15355|MIR3:MIR:SINE|23.0|-	23.0	-

```

The BAM file I inputted:
```
A00325:357:HTN5KDSXY:4:1118:7319:33144	16	1	10006	1	2S96M77N52M	*	0	0	CACTATCCCTAACACTATCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACACTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAACCCTAACCCTAACCCTAACCCTAACCCTAA	,,FFF,,,,FF::,:FF,F,::FFF:,FF,FFFFFFF,:FF:FFFFFFFFFFF:FF,FFFFFFFFFF,FFFFF,FFFF:,FFFFFFFFFFFFFFFFF:FFFFFFFFFF,:FFFFF:FFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFF	NH:i:3	HI:i:1	nM:i:5	AS:i:136	CR:Z:ACCTAAACAAAAAACA	UR:Z:AAAACAAAACCT	CY:Z:FFFFFF,FF:F:,FFF	UY:Z:FFFF:F::FF:F	GX:Z:-	GN:Z:-	sS:Z:ACCTAAACAAAAAACAAAAACAAAACCT	sQ:Z:FFFFFF,FF:F:,FFFFFFF:F::FF:F	sM:i:-1	CB:Z:-	UB:Z:-
A00325:357:HTN5KDSXY:4:2239:4942:12242	16	1	10534	255	3S96M2D21M30S	*	0	0	CGCAGTACCACCGAAATCTGTGCAGAGGAGAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGTCGCAAAGGCGCCGCGCCGGCGCAGACGCCCCCATGTACTCTGCGTTGATACCACTGCT	FFFFFFFFFFFFFF,FF:FFFFFFFFFFFFFFFFFFFFF:F:FFFFFFFFFFFF,:FFFFFFF:FFFFFFFFFFFFF:F:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:FFFFFFFFFFFFFFFF:FFFFFFFF	NH:i:1	HI:i:1	nM:i:3	AS:i:103	CR:Z:TGTTATGAGTAAGAAC	UR:Z:ACCAGCTTGTAA	CY:Z:FFF:F,FFF:FFFFFF	UY:Z:FF,::FFFFFFF	GX:Z:-	GN:Z:-	sS:Z:TGTTATGAGTAAGAACACCAGCTTGTAA	sQ:Z:FFF:F,FFF:FFFFFFFF,::FFFFFFF	sM:i:-1	CB:Z:-	UB:Z:-
A00325:357:HTN5KDSXY:4:2418:6668:4867	16	1	10536	255	94M2D26M30S	*	0	0	TACCACCGAAATCTGTGCAGAGGAGAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGCCGTCGCAAAGGCGCCGCGCCGGCGCAGACGCAGAGACCCCATGTACTCTGCGTTGATACCACTGCT	,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	NH:i:1	HI:i:1	nM:i:3	AS:i:106	CR:Z:GTGCTTAGGAGAATGC	UR:Z:TGCTCCACCTTT	CY:Z:FFFFFFFFFFFFFFFF	UY:Z:FFFFF:FFFFFF	GX:Z:-	GN:Z:-	sS:Z:GTGCTTAGGAGAATGCTGCTCCACCTTT	sQ:Z:FFFFFFFFFFFFFFFFFFFFF:FFFFFF	sM:i:-1	CB:Z:-	UB:Z:-

```

This is the output of the SoloTE tmp directory:

```
-rw-r----- 1 singhb22 Perturb-map  17M Jun 30 14:28 HTA12_25_3_allcounts.txt
-rw-r----- 1 singhb22 Perturb-map 652K Jun 30 14:28 HTA12_25_3_countpercell_10.counts
-rw-r----- 1 singhb22 Perturb-map 1.5M Jun 30 14:28 HTA12_25_3_countpercell_11.counts
-rw-r----- 1 singhb22 Perturb-map 980K Jun 30 14:28 HTA12_25_3_countpercell_12.counts
-rw-r----- 1 singhb22 Perturb-map 364K Jun 30 14:28 HTA12_25_3_countpercell_13.counts
-rw-r----- 1 singhb22 Perturb-map 541K Jun 30 14:28 HTA12_25_3_countpercell_14.counts
-rw-r----- 1 singhb22 Perturb-map 650K Jun 30 14:28 HTA12_25_3_countpercell_15.counts
-rw-r----- 1 singhb22 Perturb-map 455K Jun 30 14:28 HTA12_25_3_countpercell_16.counts
-rw-r----- 1 singhb22 Perturb-map 991K Jun 30 14:28 HTA12_25_3_countpercell_17.counts
-rw-r----- 1 singhb22 Perturb-map 276K Jun 30 14:28 HTA12_25_3_countpercell_18.counts
-rw-r----- 1 singhb22 Perturb-map 1.1M Jun 30 14:28 HTA12_25_3_countpercell_19.counts
-rw-r----- 1 singhb22 Perturb-map 1.6M Jun 30 14:28 HTA12_25_3_countpercell_1.counts
-rw-r----- 1 singhb22 Perturb-map 452K Jun 30 14:28 HTA12_25_3_countpercell_20.counts
-rw-r----- 1 singhb22 Perturb-map 154K Jun 30 14:28 HTA12_25_3_countpercell_21.counts
-rw-r----- 1 singhb22 Perturb-map 246K Jun 30 14:28 HTA12_25_3_countpercell_22.counts
-rw-r----- 1 singhb22 Perturb-map 1.3M Jun 30 14:28 HTA12_25_3_countpercell_2.counts
-rw-r----- 1 singhb22 Perturb-map 964K Jun 30 14:28 HTA12_25_3_countpercell_3.counts
-rw-r----- 1 singhb22 Perturb-map 428K Jun 30 14:28 HTA12_25_3_countpercell_4.counts
-rw-r----- 1 singhb22 Perturb-map 746K Jun 30 14:28 HTA12_25_3_countpercell_5.counts
-rw-r----- 1 singhb22 Perturb-map 790K Jun 30 14:28 HTA12_25_3_countpercell_6.counts
-rw-r----- 1 singhb22 Perturb-map 780K Jun 30 14:28 HTA12_25_3_countpercell_7.counts
-rw-r----- 1 singhb22 Perturb-map 573K Jun 30 14:28 HTA12_25_3_countpercell_8.counts
-rw-r----- 1 singhb22 Perturb-map 582K Jun 30 14:28 HTA12_25_3_countpercell_9.counts
-rw-r----- 1 singhb22 Perturb-map  360 Jun 30 14:28 HTA12_25_3_countpercell_GL000195.1.counts
-rw-r----- 1 singhb22 Perturb-map  390 Jun 30 14:28 HTA12_25_3_countpercell_GL000218.1.counts
-rw-r----- 1 singhb22 Perturb-map  120 Jun 30 14:28 HTA12_25_3_countpercell_KI270711.1.counts
-rw-r----- 1 singhb22 Perturb-map  210 Jun 30 14:28 HTA12_25_3_countpercell_KI270727.1.counts
-rw-r----- 1 singhb22 Perturb-map  120 Jun 30 14:28 HTA12_25_3_countpercell_KI270734.1.counts
-rw-r----- 1 singhb22 Perturb-map 426K Jun 30 14:28 HTA12_25_3_countpercell_MT.counts
-rw-r----- 1 singhb22 Perturb-map 408K Jun 30 14:28 HTA12_25_3_countpercell_X.counts
-rw-r----- 1 singhb22 Perturb-map  22K Jun 30 14:28 HTA12_25_3_countpercell_Y.counts
-rw-r----- 1 singhb22 Perturb-map 150M Jun 30 14:28 HTA12_25_3_final.bam
-rw-r----- 1 singhb22 Perturb-map 1.9M Jun 30 14:28 HTA12_25_3_final.bam.bai
-rw-r----- 1 singhb22 Perturb-map 3.4K Jun 30 14:20 HTA12_25_3_nogenes_overlappingtes.bam
-rw-r----- 1 singhb22 Perturb-map 1.6K Jun 30 14:20 HTA12_25_3_nogenes_overlappingtes.bam.bai
-rw-r----- 1 singhb22 Perturb-map    0 Jun 30 14:20 HTA12_25_3_nogenes_overlappingtes.bed
-rw-r----- 1 singhb22 Perturb-map    0 Jun 30 14:20 HTA12_25_3_selectedtes.bed
-rw-r----- 1 singhb22 Perturb-map 3.4K Jun 30 14:20 HTA12_25_3_teannotated.bam
-rw-r----- 1 singhb22 Perturb-map 3.4K Jun 30 14:20 temp_annotated_te.bam
```

Furthermore, here are the other tests you asked for in the previous GitHub issue:

```
samtools view --min-MQ 255 -c HTA12_25_3_GDC38.Aligned.sortedByCoord.out.bam 
207104916
```

```
samtools view HTA12_25_3_GDC38.Aligned.sortedByCoord.out.bam |awk '{print $5}'|sort|uniq -c
5183908 0
2057099 1
207104916 255
3935049 3
```

Please let me know what I should do. Should I be running the previous version of SoloTE, version 1.10, like issue #41 ? Or is it an issue with the BED file/BAM, like when the "chr" needs to be renamed in issue #2?  

As a note, this particular file is single-nucleus data, not single-cell. Would this be impacting the results?

**Comment by singhbhavya** [comment]
Hi! I re-ran SoloTE after fixing the repeatmasker BED file, and it ran successfully. The output is very strange though, and I'm confused about the very high number of TEs. Is this normal? Also, the temp directory was not automatically deleted - is this normal too?

```
A total of 3988039 UMIs are in the final matrix.
Of these,
        1069364 (26.814%) correspond to genes.
        and 2918675 (73.186%) correspond to TEs.
TE detected UMIs are distributed as follows:
        Locus-specific TEs: 2736111 UMIs (93.745%).
        Subfamily TEs: 182564 (6.255%).

```

I have another question. Is gene information preserved in the outputted matrices? Or does it only include TEs? Can it be treated as a normal anndata file with gene+TE information?

**Comment by bvaldebenitom** [comment]
Hi @singhbhavya !

Sorry for the delay in answering. Please let me know if I missed something.

Regarding `--soloMultiMappers EM` it is a feature available by STAR. I did some tests (nothing very formal) and you would either need to add TE annotation as part of the gene GTF during genome indexing or "on the fly" during alignment. I haven't benchmarked its accuracy with TE detection since I thought manipulating the GTF files to make it work is less straight-forward than the current SoloTE implementation.

It seems you were getting the error due to mismatch between the chromosome IDs in the BAM and BED file, so I'm glad you were able to solve it. Regarding the questions:

> The output is very strange though, and I'm confused about the very high number of TEs. Is this normal?

What exactly is it that you think is strange? Just the high number of TEs? I wouldn't say it is normal, because I often get between 20%-30% of TEs in these analysis, or even less. 

What genome are you using in your analyses, and what GTF annotation are you using? I think this is one of the main factors causing differences in the number of UMIs assigned to genes. Since you have the Cell Ranger output, once you load it in Seurat or Scanpy, you can sum the entire matrix, and check if that number is similar to the one in the SoloTE output.

> Also, the temp directory was not automatically deleted - is this normal too?

Yes. I haven't make it so it deletes the temporary files automatically, since some times error during the final processing would cause anabrupt finish, and having the BAM files already processed speeds up a later re-run when the issues are fixed. For example, with the "chr" issue above, it would have repeated everything from the beginning. I will add this to the next version so there are proper validations and temporary files removed automatically in the case of a successful run.

> Is gene information preserved in the outputted matrices? Or does it only include TEs? Can it be treated as a normal anndata file with gene+TE information?

Yes! This is one of the main advantages. With SoloTE you get a gene+TE matrix, which you can process normally. Then, you can quickly check TEs since they all have "SoloTE" at the beginning of their identifier.

**Comment by singhbhavya** [comment]
I'm actually referring to using `--soloMultiMappers EM` as a part of the STAR alignment to hg38, without repeatmasker, prior to SoloTE. I think it could potentially be useful compared to using `--outMultimapperOrder Random`, or used in combination?  I'm unsure if these two would be in fonlict with each other.

Yes, I think the high number of TEs is strange. I've seen this case for all my samples (11), where the TE % is about 75%, and genes are about 25%. I'm not sure why the outputs look like this, and I think I'll need to modify how I run STAR.

I'm using the hg38 genome and annotation.

Thank you so much for the clarification regarding the temporary directory and the matrices!

**Comment by bvaldebenitom** [comment]
I don't recall if these options are actually in conflict with each other, but I previously asked Alex Dobin (the STAR developer) [about whether the soloMultiMappers flags changed anything in the BAM, and they don't](https://github.com/alexdobin/STAR/issues/1438#issuecomment-1008164941). Since SoloTE processes the BAM files, this is why the option wouldn't impact the way TE expression is currently estimated.

Regarding the outputs, do you get proper gene expression numbers from any of the matrices?

**Comment by singhbhavya** [comment]
Hi there! Confirming that the matrices look okay. The snRNA-seq samples have a 75% TEs & 25% genes read distribution, but the scRNA-seq samples have 75% genes and 25% TEs. The scRNA-seq read distribution is likely because of un-spliced RNA in the nucleus.

**Comment by bvaldebenitom** [comment]
Hi @singhbhavya,

Thanks for the information, and I agree that the issue is related to un-spliced RNA. Still interesting though!
