### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by A1aNNN** [bvaldebenitom/SoloTE#5]
Hi there,

I've been trying to run the SoloTE script on a BED file and a BAM file that I received from STAR with the parameters **--winAnchorMultimapNmax 100**, **--outFilterMultimapNmax 100**, and **--outSAMmultNmax 1**, but received an error that it's unable to print(samtags_from_star[0]).

Just wondering if you had any test data that I could use to run SoloTE on, and whether the expected outputs for SoloTE are the files **barcodes.tsv.gz**, **features.tsv.gz**, and **matrix.mtx.gz**.

Thanks,

Alan Wang

<img width="1826" alt="Screen Shot 2022-11-08 at 2 50 44 PM" src="https://user-images.githubusercontent.com/86388978/200693123-626c80e2-7ae5-41ba-8867-45d99d0043cc.png">

**Comment by bvaldebenitom** [comment]
Hi Alan,

if you are using STAR for single cell RNA-Seq analysis, you should also include the `outSAMattributes` options to include the CB, UB, CR and UR tags for each alignment, as indicated in the [STAR solo documentation](https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#bam-tags).

We will add a sample BAM file to test the pipeline.

If there is anything else, please reach out.

**Comment by A1aNNN** [comment]
Thanks for your help! Greatly appreciate your time
