### ISSUE TITLE
SoloTE compatibility with Souporcell

### ISSUE THREAD

**Issue by nickliotta** [bvaldebenitom/SoloTE#52]
Hello,

I'm currently in the process of trying to use the SoloTE pipeline on demultiplexed samples from a paper where I'm trying to analyze locus-specific TE expression. What I am trying to do is run STARsolo, Souporcell for demultiplexing, then SoloTE, but this would not be possible because SoloTE does not have the option to provide a list of barcodes to detect TE expression. Is there a suggested way I could go about this? The original paper in Nature demultiplexed the samples after using SoloTE, but that was with a provided .bam file from the demultiplexer. The original paper from the samples I'm analyzing used Souporcell, so I am trying to replicate their analysis all the way until analyzing the TE expression. I realized this was an issue when I ran SoloTE on STARsolo output and then I was going to subset the SoloTE output based on the barcode-specific clusters from Souporcell, but then I noticed SoloTE doesn't support a custom barcode list. Using the Souporcell .bam file lead to SoloTE not recognizing any locus-specific TE's (only subfamily). Thank you for providing such a great program and hope there is a solution to this! If there is anything I can provide please let me know.

**Comment by bvaldebenitom** [comment]
Hi!

Could you share the link to the paper?

Thanks,
Braulio.

**Comment by nickliotta** [comment]
@bvaldebenitom Thank you so much for the fast reply! The paper is here https://doi.org/10.1016/j.cels.2024.04.002 . The pipeline I replicated is under the supplemental information, Figure S2. I am having trouble figuring out where to station the SoloTE aspect within the pipeline.

(Accidentally closed it ignore that)

**Comment by bvaldebenitom** [comment]
Hi @nickliotta 

sorry for taking long in answering.

I would run SoloTE on the STARsolo BAM files. Then, on Seurat you follow the same protocol as in the paper, load the SoloTE outputs, and merge the SoloTE and Seurat matrices on the barcodes post-Souporcell and post-QC.

Let me know if this helps.
