### ISSUE TITLE
annotate_BAM.py doesn't exist?

### ISSUE THREAD

**Issue by murphytho** [bvaldebenitom/SoloTE#54]
Hi there, 

I'm getting a strange error when trying to run SoloTE. I will post all the traceback below, but best I can tell, the problem starts here every time I run the program:
`python: can't open file 'SoloTE/annotateBAM.py': [Errno 2] No such file or directory`

The file certainly exists and is exactly where I say it is. I tried moving all my files into the SoloTE folder and got the same error (except it said "/annotateBAM.py" didn't exist. I've tried moving all over the place and every time, the path is correct but the file cannot be found.

Appreciate your help!

Here is the full traceback:

`python3 SoloTE/SoloTE_pipeline.py --threads 4 --bam SRR13199080_Aligned.sortedByCoord.out.bam --teannotation SoloTE/hg38_rmsk.bed --outputprefix SRR13199080 --outputdir soloTE_out/
SoloTE started at 16:52:50
[OK] samtools found!
[OK] bedtools found!
SoloTE v1.10 started!
SoloTE Home directory SoloTE
SoloTE executed from /media/thomas/Elements/single_cell_test
Results will be stored in /media/thomas/Elements/single_cell_test/soloTE_out
Input BAM file: /media/thomas/Elements/single_cell_test/SRR13199080_Aligned.sortedByCoord.out.bam
Input TE BED file: /media/thomas/Elements/single_cell_test/SoloTE/hg38_rmsk.bed
Currently working in temporary directory: /media/thomas/Elements/single_cell_test/soloTE_out/SRR13199080_SoloTE_temp
samtools view -@ 4 -O BAM -o SRR13199080_nogenes_overlappingtes.bam -L /media/thomas/Elements/single_cell_test/SoloTE/hg38_rmsk.bed -e '(exists([CB]) && exists([UB]) && [CB]!="-" && [UB]!="-") && (!exists([GN]) || [GN]=="-")' /media/thomas/Elements/single_cell_test/SRR13199080_Aligned.sortedByCoord.out.bam
samtools index SRR13199080_nogenes_overlappingtes.bam
bedtools bamtobed -i SRR13199080_nogenes_overlappingtes.bam -split > SRR13199080_nogenes_overlappingtes.bed
bedtools intersect -a /media/thomas/Elements/single_cell_test/SoloTE/hg38_rmsk.bed -b SRR13199080_nogenes_overlappingtes.bed -u > SRR13199080_selectedtes.bed
python SoloTE/annotateBAM.py SRR13199080_nogenes_overlappingtes.bam SRR13199080_selectedtes.bed temp_annotated_te.bam 1
python: can't open file 'SoloTE/annotateBAM.py': [Errno 2] No such file or directory
samtools sort -@ 4 -O BAM -o SRR13199080_teannotated.bam temp_annotated_te.bam
[E::hts_open_format] Failed to open file "temp_annotated_te.bam" : No such file or directory
samtools sort: can't open "temp_annotated_te.bam": No such file or directory
samtools merge --threads 4 -o - /media/thomas/Elements/single_cell_test/SRR13199080_Aligned.sortedByCoord.out.bam SRR13199080_teannotated.bam|samtools view -@ 4 -O BAM -o SRR13199080_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
[E::hts_open_format] Failed to open file "SRR13199080_teannotated.bam" : No such file or directory
samtools merge: fail to open "SRR13199080_teannotated.bam": No such file or directory
[main_samview] fail to read the header from "-".
samtools index SRR13199080_final.bam
[E::hts_open_format] Failed to open file "SRR13199080_final.bam" : No such file or directory
samtools index: failed to open "SRR13199080_final.bam": No such file or directory
[E::hts_open] fail to open file 'SRR13199080_final.bam'
Traceback (most recent call last):
  File "SoloTE/SoloTE_pipeline.py", line 187, in <module>
    for chromosome_info in pysam.idxstats(final_bam).split("\n"):
  File "/home/thomas/miniconda3/envs/SoloTE/lib/python3.6/site-packages/pysam/__init__.py", line 71, in __call__
    (retval, "\n".join(stderr)))`

**Comment by bvaldebenitom** [comment]
Hi @murphytho !

Thanks for using SoloTE.

What operating system and what python version are you using?

**Comment by murphytho** [comment]
Thanks for getting back to me! I'm using Ubuntu 24. I found that issue I think... I had updated python to 3.9.5 in my conda environment, but at some point I had reverted it somehow (maybe I did a fresh install? not sure) all the way back to python 3.6. Sorry about that.

I corrected the python version and do not seem to be getting the error anymore, go figure. However, I'm still not seeing the program finish properly. Below is the error. Please let me know if you need anything else to figure it out!

`(SoloTE) thomas@thomas-System-Product-Name:/media/thomas/Elements/single_cell_test$ python3 /home/thomas/Desktop/SoloTE/SoloTE_pipeline.py --threads 8 --bam HERV_STAR_solo_output/SRR13199080_Aligned.sortedByCoord.out.bam --teannotation refs/hg38_rmsk.bed --outputprefix SRR13199080 --outputdir soloTE_out/
SoloTE started at 16:16:46
[OK] samtools found!
[OK] bedtools found!
SoloTE v1.10 started!
SoloTE Home directory /home/thomas/Desktop/SoloTE
SoloTE executed from /media/thomas/Elements/single_cell_test
Results will be stored in /media/thomas/Elements/single_cell_test/soloTE_out
Input BAM file: /media/thomas/Elements/single_cell_test/HERV_STAR_solo_output/SRR13199080_Aligned.sortedByCoord.out.bam
Input TE BED file: /media/thomas/Elements/single_cell_test/refs/hg38_rmsk.bed
Currently working in temporary directory: /media/thomas/Elements/single_cell_test/soloTE_out/SRR13199080_SoloTE_temp
samtools view -@ 8 -O BAM -o SRR13199080_nogenes_overlappingtes.bam -L /media/thomas/Elements/single_cell_test/refs/hg38_rmsk.bed -e '(exists([CB]) && exists([UB]) && [CB]!="-" && [UB]!="-") && (!exists([GN]) || [GN]=="-")' /media/thomas/Elements/single_cell_test/HERV_STAR_solo_output/SRR13199080_Aligned.sortedByCoord.out.bam
samtools index SRR13199080_nogenes_overlappingtes.bam
bedtools bamtobed -i SRR13199080_nogenes_overlappingtes.bam -split > SRR13199080_nogenes_overlappingtes.bed
bedtools intersect -a /media/thomas/Elements/single_cell_test/refs/hg38_rmsk.bed -b SRR13199080_nogenes_overlappingtes.bed -u > SRR13199080_selectedtes.bed
python /home/thomas/Desktop/SoloTE/annotateBAM.py SRR13199080_nogenes_overlappingtes.bam SRR13199080_selectedtes.bed temp_annotated_te.bam 1
samtools sort -@ 8 -O BAM -o SRR13199080_teannotated.bam temp_annotated_te.bam
samtools merge --threads 8 -o - /media/thomas/Elements/single_cell_test/HERV_STAR_solo_output/SRR13199080_Aligned.sortedByCoord.out.bam SRR13199080_teannotated.bam|samtools view -@ 8 -O BAM -o SRR13199080_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index SRR13199080_final.bam
Traceback (most recent call last):
  File "/home/thomas/Desktop/SoloTE/SoloTE_pipeline.py", line 214, in <module>
    allcounts = pd.read_table(allcountsfile,header=None)
  File "/home/thomas/miniconda3/envs/SoloTE/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/home/thomas/miniconda3/envs/SoloTE/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/thomas/miniconda3/envs/SoloTE/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/thomas/miniconda3/envs/SoloTE/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/thomas/miniconda3/envs/SoloTE/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'SRR13199080_allcounts.txt'`

**Comment by bvaldebenitom** [comment]
@murphytho,

thanks for reporting back. I remember seeing some issues in certain operating systems, but glad that you worked it out.

Could you share the output of `ls -lht /media/thomas/Elements/single_cell_test/soloTE_out/SRR13199080_SoloTE_temp`? There might be something going on with intermediate files.

**Comment by murphytho** [comment]
Absolutely. Seems like that file is indeed missing, but I'm not sure why/what should be creating it. 

ls -lht /media/thomas/Elements/single_cell_test/soloTE_out/SRR13199080_SoloTE_temp
total 24K
-rw-rw-r-- 1 thomas thomas 1.6K Oct  4 16:28 SRR13199080_final.bam.bai
-rw-rw-r-- 1 thomas thomas 3.1K Oct  4 16:28 SRR13199080_final.bam
-rw-rw-r-- 1 thomas thomas 3.1K Oct  4 16:21 SRR13199080_teannotated.bam
-rw-rw-r-- 1 thomas thomas 3.2K Oct  4 16:21 temp_annotated_te.bam
-rw-rw-r-- 1 thomas thomas    0 Oct  4 16:21 SRR13199080_selectedtes.bed
-rw-rw-r-- 1 thomas thomas    0 Oct  4 16:21 SRR13199080_nogenes_overlappingtes.bed
-rw-rw-r-- 1 thomas thomas 1.6K Oct  4 16:21 SRR13199080_nogenes_overlappingtes.bam.bai
-rw-rw-r-- 1 thomas thomas 3.2K Oct  4 16:21 SRR13199080_nogenes_overlappingtes.bam

**Comment by bvaldebenitom** [comment]
Try removing the entire temp directory with
`rm -Rf /media/thomas/Elements/single_cell_test/soloTE_out/SRR13199080_SoloTE_temp`
and then running SoloTE with the same command you were using.

Right now, it looks like no TEs are being found (`SRR13199080_selectedtes.bed` is empty). Can you also verify that the chromosome IDs in the BAM file match those in the BED file? You can copy the output of
`samtools view /media/thomas/Elements/single_cell_test/SRR13199080_Aligned.sortedByCoord.out.bam|head`
and
`head refs/hg38_rmsk.bed`

**Comment by murphytho** [comment]
To the first, deleting that directory has no effect, I still get the same allcounts.txt error

For the second request, here are the heads. Seems like they are both chr1?  My STAR alignment was done to a reference file called 'GRCh38_primary_assembly.fa' from gencode GRCh39p14 (release 46)(https://www.gencodegenes.org/human/). And the rmsk bed file was made from SoloTE's script. My understanding was that they should be compatible but perhaps somehow they are not? I have run into problems when using other tools with mismatched files and could never figure out why, but typically they finished running and simply had blank (or near blank) output. If you have a source for a 'known good reference fasta and think that could be an issue, let me know. 

`samtools view /media/thomas/Elements/single_cell_test/SRR13199080_Aligned.sortedByCoord.out.bam|head > bamhead.txt`
SRR13199080.298533216	0	chr1	12613	1	2S96M	*	0	0	CAGTGTGTGGTGATGCCAGGCATGCCATTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGAGTCCC	AAA///EEEA/E/E/EEEEEEEE/EE/<AE/E/AE//EEE</EEEEAE<<AEEEE<AE<EE</<EEE/E</A<//</EE//AEAE</6///A//EE/6	NH:i:4	HI:i:1	AS:i:90	nM:i:2
SRR13199080.65487439	0	chr1	12620	1	98M	*	0	0	GTGATGCCAGGCATGCCCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGCCTTGGCTCACACTCTTGTGAGTGTCCCCAGTGTTGC	AAA/AEEEEEEE/EEEEEAEEEEEEEEE<EEE<EEEEE/AE<EEAEEE/AA<EE<EEEEEE/EAEAE/EEEEEE<E<</A/6AEAEEAEEEAEAEEEE	NH:i:4	HI:i:1	AS:i:92	nM:i:2
SRR13199080.16542823	0	chr1	12628	1	94M499N4M	*	0	0	AGGCATGCCCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGACGACGACGGCCGCCTTGGATCACACTCTTGTGCGTGTCCCCAGTGTTGCAGAGGCAG	A6/AAE/EEEEEEEEE/AE/EEE/EEE6EEE/EAE<<EEAE///AAE/AEEAE//AA/</EE/A6A/AEE<A///</<E/AE//AAEEAA<//6/<</	NH:i:3	HI:i:1	AS:i:92	nM:i:3
SRR13199080.196228531	16	chr1	12799	1	98M	*	0	0	AGAGGCTTTGATGCCCCTCCACACCCTCTTGATCTTCCCTGTGATGTCATCTGGAGCCCTGCTGCTTGCGGTGGCCTATAAAGCCTCCTAGTCTGGCT	/6//E///6//AA/EE<E</A<EAA////A<////E/E<<</</<<<<<///<</E<EAEE/EE/AEE/EE/AE/EEAA<6EEEEAAEE6E<AAAAA6	NH:i:3	HI:i:1	AS:i:94	nM:i:1
SRR13199080.64915579	16	chr1	13858	1	98M	*	0	0	TATAATAACTAAAGTTAGCTGCCCTGGACTATTCACCCCCTAGTCTCAATTTAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGTCAC	/<<<6</</6<6</AAAE/EEAA/</EE/E//6/AEAEA/A/AE///</E/EAA//<//E/AA<<E<A<<E/A</E/E/AEE//EAE/EE/A/A/6A/	NH:i:3	HI:i:1	AS:i:96	nM:i:0
SRR13199080.201424239	16	chr1	13858	1	98M	*	0	0	TATAATAACTAAAGTTAGCTGCCCTGGACTATTCACCCCCTAGTCTCAATTTAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGTCAC	E<AA6/<EEAA<<EEEEAEEEEE<EEEEEEEEEEEEAEEA<AEAEEEEAE6//AEEEEEEEEEEEAEEEEEAEEAEEEEEEEEEEEEAEE</EAAAAA	NH:i:3	HI:i:1	AS:i:96	nM:i:0
SRR13199080.234286473	16	chr1	13861	1	98M	*	0	0	AATAACTAAAGTTAGCTGCCCTGGACTATTCACCCCCTAGTCTCAATTTAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGTCACCTC	6//6</<6/<A/<6E/EAA</A/A</A/6A/E/</E/<6<E/<<A///A6</6/////<A//E<EAA//AE<E<AEEAEAA<EAAEE///AEAAAAAA	NH:i:3	HI:i:1	AS:i:96	nM:i:0
SRR13199080.372312710	16	chr1	13861	1	98M	*	0	0	AATAACTAAAGTTAGCTGCCCTGGACTATTCACCCCCTAGTCTCAATTTAAGAAGATCCCCATGGCCACAGGGCCCCTGCCTGGGGGCTTGTCACCTC	6/AA<<A66<<A<<E<<E/AA<<AEAEAEEAE/E<EAE<AA6/<AA6A<</E<AAAEEEEEA<<EEAE/EEEEEEEEEEEEEAEEEE//AA<AAAAAA	NH:i:3	HI:i:1	AS:i:96	nM:i:0
SRR13199080.279807640	0	chr1	14039	0	98M	*	0	0	GCTTGGTGCCGGTTCCTCCAAGTCGCTGGCACCTCCCTCCCTCTCAGCCACTTGAGCAAGCTCCAAGACATCGTCTACCGCGACACCAGCAATTGTGC	A</<AE/</</A//A//////A/EA/6AE//////A//6/6/</6////////6//////E6/A//A/A/6A//<<//A/A/////6/<A///<<AA/	NH:i:6	HI:i:1	AS:i:82	nM:i:7
SRR13199080.160709322	0	chr1	14057	0	98M	*	0	0	CAAGTCGATCGCACCTCCCTGCCTCTCAACCACTTGAGCAAACTGCAAGACATCGTCTACCCCAACACCAGCAAGAGTGCGAAGGGCCAGTAGGCTCT	////AEEA//<//E//A/E//E/AEE////E/A/<E/EE///EE/E/<<///E///E////////<//A/EE<///A/A//<<///////EEEEA<A/	NH:i:6	HI:i:1	AS:i:80	nM:i:8

`head refs/hg38_rmsk.bed`
chr1	11505	11675	chr1|11505|11675|L1MC5a:L1:LINE|25.1|-	25.1	-
chr1	11678	11780	chr1|11678|11780|MER5B:hAT-Charlie:DNA|29.4|-	29.4	-
chr1	15265	15355	chr1|15265|15355|MIR3:MIR:SINE|23.0|-	23.0	-
chr1	18907	19048	chr1|18907|19048|L2a:L2:LINE|33.8|+	33.8	+
chr1	19972	20405	chr1|19972|20405|L3:CR1:LINE|31.2|+	31.2	+
chr1	20531	20679	chr1|20531|20679|Plat_L3:CR1:LINE|33.1|+	33.1	+
chr1	21949	22075	chr1|21949|22075|MLT1K:ERVL-MaLR:LTR|27.9|+	27.9	+
chr1	23120	23371	chr1|23120|23371|MIR:MIR:SINE|28.2|-	28.2	-
chr1	23804	24038	chr1|23804|24038|L2b:L2:LINE|28.4|+	28.4	+
chr1	24088	24250	chr1|24088|24250|MIR:MIR:SINE|24.2|+	24.2	+

I appreciate your time on this, we are trying to get this and other single cell pipelines up and running and I am run thin!

**Comment by bvaldebenitom** [comment]
@murphytho,

I think the issue is that the BAM file is lacking the CB and UB tags. Briefly, during the alignment process with STAR, you need to specify
`--outSAMattributes NH HI nM AS CR UR CY UY CB UB GX GN sS sQ sM`

Once you have this new alignment, delete the directories and run the pipeline from the beginning again.

I will check for differences between the Gencode genome, but I usually work with all the data from UCSC.

**Comment by murphytho** [comment]
Got it. As I'm sure you can tell, I'm new to STARsolo. I'm guessing those tags are quite important for downstream. My new command for STAR looks like this:

`STAR --runThreadN 10 --genomeDir refs/index/ --readFilesIn reads/SRR13199080_2.fastq.gz reads/SRR13199080_1.fastq.gz --readFilesCommand zcat --outSAMtype BAM SortedByCoordinate --outFileNamePrefix HERV_STAR_solo_output/SRR13199080_new_ --winAnchorMultimapNmax 100 --outFilterMultimapNmax 100 --outSAMmultNmax 1 --outSAMattributes NH HI nM AS CR UR CY UY CB UB GX GN sS sQ sM --soloType CB_UMI_Simple --soloCBwhitelist refs/737K-august-2016.txt --soloCellFilter  EmptyDrops_CR`

I will let this run and try SoloTE fresh after. Thank you again for bearing with me!

**Comment by murphytho** [comment]
Hi again! Looks like I have a successful run with the new BAM. Thanks so much for your help!
