### ISSUE TITLE
Samtools error

### ISSUE THREAD

**Issue by vinothkr11** [bvaldebenitom/SoloTE#56]
Dear @bvaldebenitom ,
I am using SoloTE version 1.10.
This is the input
`python SoloTE_pipeline.py --threads 320 --bam /scratch/j/jczplab/vrajan11/lineage-2024/GEX-BAM/d3r1b1.bam --teannotation hg38_rmsk.bed --outputprefix d3r1b1 --outputdir d3r1b1`

This is the error message I get
samtools sort -@ 320 -O BAM -o d3r1b1_teannotated.bam temp_annotated_te.bam
samtools merge --threads 320 -o - /scratch/j/jczplab/vrajan11/lineage-2024/GEX-BAM/d3r1b1.bam d3r1b1_teannotated.bam|samtools view -@ 320 -O BAM -o d3r1b1_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index d3r1b1_final.bam
Traceback (most recent call last):
File "/gpfs/fs0/scratch/j/jczplab/vrajan11/TE_10_24/SoloTE_pipeline.py", line 187, in
for chromosome_info in pysam.idxstats(final_bam).split("\n"):
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/gpfs/fs0/scratch/j/jczplab/vrajan11/cospar_kernel/lib/python3.11/site-packages/pysam/utils.py", line 83, in call
raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools idxstats: failed to open "d3r1b1_final.bam": No such file or directory\n'

The following are the versions of samtools and bedtools: samtools/1.20 and bedtools/2.31.0. I have tried samtools/1.16.1 and an earlier version of bedtools, which produced the same output. Please help

**Comment by bvaldebenitom** [comment]
Hi @vinothkr11 

could you please report the result of `ls -Rlht d3r1b1`?

It looks like it might have failed generating the final BAM file.

**Comment by vinothkr11** [comment]
Thank you for your response. Here is the output
d3r1b1:
total 512
drwxr-s--- 2 vrajan11 jczplab 4.0K Oct  8 21:27 d3r1b1_SoloTE_temp

d3r1b1/d3r1b1_SoloTE_temp:
total 12G
-rw-r----- 1 vrajan11 jczplab 3.9G Oct  9 00:20 temp_annotated_te.bam
-rw-r----- 1 vrajan11 jczplab 103M Oct  8 13:46 d3r1b1_selectedtes.bed
-rw-r----- 1 vrajan11 jczplab 4.6G Oct  8 13:44 d3r1b1_nogenes_overlappingtes.bed
-rw-r----- 1 vrajan11 jczplab 5.6M Oct  8 13:41 d3r1b1_nogenes_overlappingtes.bam.bai
-rw-r----- 1 vrajan11 jczplab 3.3G Oct  8 13:40 d3r1b1_nogenes_overlappingtes.bam

**Comment by vinothkr11** [comment]
Thank you @bvaldebenitom for help. I think I figured this out. The pipeline was overwhelmed with the amount of threads that I was using, reducing it made the run smooth. 

I have a follow-up question, very similar to question #42. I want a count matrix that only has the TE annotations and without the gene quantification, such that I can use TE as a separate assay in Seurat. 

Do you think, avoiding the merge step and using the _teannotated.bam file for the downstream processing will work in this case?

**Comment by bvaldebenitom** [comment]
Hi @vinothkr11 

thanks for letting me know about the solution to your issue.

As for creating independent matrices by genes and TEs, I would do this: 

```
library(Seurat)
mat <- Read10X("PATH TO YOUR SOLOTE OUTPUT")
dim(mat)
#[1] 244515   4992
##get the gene-only matrix 
gene_mat <- mat[grep("SoloTE",rownames(mat),invert=TRUE),]
##get the TE-only matrix
te_mat <- mat[grep("SoloTE",rownames(mat),invert=FALSE),]
dim(gene_mat)
##[1] 29302  4992
dim(te_mat)
##[1] 215213   4992
```

This method doesn't require additional pipeline runs, and I think it is more straightforward.

Let me know if this works. I have done this for my previous works successfully.

**Comment by vinothkr11** [comment]
Thank you @bvaldebenitom, this works. I am closing the issue.
