### ISSUE TITLE
Question about gene quantification, chimeric gene counts?

### ISSUE THREAD

**Issue by Nieto-CaballeroVE** [bvaldebenitom/SoloTE#58]
Hi,

Thank you for developing this tool. I have a question regarding the output. I noticed that the number of features, excluding TEs, is significantly higher than the number of genes in the count matrix from Cell Ranger. This seems to be due to some genes appearing as duplicates in the soloTE output.

For example, there are counts for "ALDH3A2" and "SLC47A1," but there is also a feature listed as "ALDH3A2;SLC47A1."

I’m having trouble understanding why soloTE generates these additional features. Could you help me understand this behavior?

All the best,
Victor

**Comment by bvaldebenitom** [comment]
Hi @Nieto-CaballeroVE !

Can you share the software and parameters used for alignment? That will play a huge impact on the generation of counts having identifiers like the one you describe.

**Comment by Nieto-CaballeroVE** [comment]
Hi @bvaldebenitom,

Thanks for your response. We used `cellranger-arc count` , version is 2.0.2

**Comment by bvaldebenitom** [comment]
Thanks, now I understand. SoloTE processes the "GN" tag in the BAM file, which is dependent on the alignment tool. In particular, CellRanger assigns in this tag a list of genes "compatible with the alignment" (see https://www.10xgenomics.com/support/software/cell-ranger-arc/latest/analysis/barcoded-bam#bam-alignment-tags) **separated with semicolon**. 

Altogether, these features could just be removed during post-processing in Seurat with something like:
`
count_matrix <- count_matrix[grep(";",rownames(count_matrix),invert=TRUE),]`

I can also make an update to SoloTE to just remove these counts too if that's more convenient, but either way should result in the same matrix.
