### ISSUE TITLE
CellRanger bam file

### ISSUE THREAD

**Issue by A1aNNN** [bvaldebenitom/SoloTE#6]
Thanks for the SoloTE tool! A question that I have is that I've been trying to run SoloTE on a bam file produced from CellRanger count, but I keep receiving this error message. Just wondering if you have any advice on how to resolve this as I believe that **outSAMmultNmax** is a parameter within STAR, and SoloTE should be able to take in bam files from both STARSolo and CellRanger.

Thanks in advance!

<img width="1305" alt="Screen Shot 2022-12-15 at 3 33 50 PM" src="https://user-images.githubusercontent.com/86388978/207989268-ae79d4b3-517b-4d56-8d9f-cfe631e86659.png">

**Comment by bvaldebenitom** [comment]
Hi @A1aNNN !

Thanks for the feedback. We have fixed this in release 1.03. Please [see instructions here](https://github.com/bvaldebenitom/SoloTE/releases/tag/1.03), as we updated the command line execution of SoloTE.

Please let us know if find any other issue.

**Comment by wjbsb** [comment]
Hello,

I have the same error in the 1.08 version but I used STARsolo v2.7.10b.

I updated the command line in the pipeline (line 110 to 114) and after it's worked.
