### ISSUE TITLE
Some required files were not written.

### ISSUE THREAD

**Issue by Zhangcy018** [bvaldebenitom/SoloTE#7]
First of all,thanks for your SoloTE! 
Sorry to bother you, but I have some problems when I run the  python script.The cellranger output BAM file became one of the input files of SoloTE，while the BED file of TEs was processed by myself according to the sample format of README.md file.But the script finally reports  errors as shown in the figure below.It seems like some required files were not written,such as  "_nogenes_overlappingtes.bed","_selectedtes.bed"and so on.Is there anything wrong with my TE_bed,or something else?

I‘d appreciate it if you could give me some advice!

![图片2](https://user-images.githubusercontent.com/121594085/209910607-58561bb8-5c6f-45d2-bf5d-9f0215b32af0.png)

**Comment by bvaldebenitom** [comment]
Hi @Zhangcy018!

Could you share the first lines of your TE BED file, and also the first lines of the output of `samtools view` on the BAM file you used?

**Comment by Zhangcy018** [comment]
Thanks for your reply！Here are the first lines.

![image](https://user-images.githubusercontent.com/121594085/210027696-0a734a0e-30e1-456f-970f-591782e28901.png)

![image](https://user-images.githubusercontent.com/121594085/210027662-e6881a55-66a2-4643-81b8-6efed969dd73.png)

By the way,I use the human T2T genome and  PBMC scRNA-seq to have a try.And I use your convertRMOut_to_SoloTEinput.sh script to convert the genome's repeatmasker.out file into a BED file. Finally, the same error occurred.

**Comment by bvaldebenitom** [comment]
Sure, happy to help!

Could you share the command you use to run SoloTE? We recently made some bug fixes for release 1.03 (available [here](https://github.com/bvaldebenitom/SoloTE/releases/tag/1.03https://github.com/bvaldebenitom/SoloTE/releases/tag/1.03)), because there were some problems with CellRanger BAM files. 

Keep in mind that we also updated the command line execution of the pipeline in release 1.03, and you would need to run the pipeline like this:
`python SoloTE_pipeline.py --threads NumberOfThreads --bam BAMfile --teannotation BEDfile --outputprefix Prefix --outputdir OutputDirectory`

Finally, if it is possible, can you share a subset of your data for debugging purposes? For example, only the Chr01 information from both the BED and the BAM files.

**Comment by Zhangcy018** [comment]
First of all, I wish you a happy New Year and thank you for handling my problems on this happy day. Surely, I noticed the latest version 1.03. And here is my command to run the script：

nohup python ~/software/SoloTE-main/SoloTE_1.03/SoloTE_pipeline.py -b data_pre/possorted_genome_bam.bam  -t 30 -d gynpe_scte.v3  -a te.bed -o gynpe &

Finally, I will share my data with you through the email left in your published articles.(braulio.valdebenitomaturana@mssm.edu)
Thank you for your generosity. Have a nice day again！

**Comment by bvaldebenitom** [comment]
Thank you for the kind wishes, hope you had a happy New Year!

The command looks good. I have not received the files yet, so when you do send them, let me know so I can confirm you that I got them correctly.

**Comment by Zhangcy018** [comment]
Also thank you for your wishes!

I sent the file to the email（braulio.valdebenitomaturana@mssm.edu） yesterday.And The title of my email is “Data of BED and BAM files”.

**Comment by bvaldebenitom** [comment]
Dear @Zhangcy018,

please see [release 1.04](https://github.com/bvaldebenitom/SoloTE/releases/tag/1.04). There was a bug when generating the count matrix. I tested this new version on the files you sent, and it is now working.

Please give it a try and let me know! If you still have the SoloTE temp folder, it should start right after processing the BAM files.

**Comment by Zhangcy018** [comment]
Thanks for the new version！

But It still didn't work in the end with my compelete data.Then I tried to use the data of Chr01, hoping it could work as you said, but unfortunately it could not.The errors are still the same as before. I checked the version ,and I noticed that some files are still not written.

Could you please tell me if you have done anything with the files I sent you or whether there are details I didn't notice？

**Comment by bvaldebenitom** [comment]
Really sorry to read this. There was nothing else done for the files you sent me.

Could you check the output of `samtools --version` and `bedtools --version`?

Could you test again in a different folder (i.e., changing the values of the `--outputdir` and `--outputprefix` options)?

**Comment by Zhangcy018** [comment]
Thanks for your advice!

The version of samtools is 1.16.1 and that of bedtools is 2.30.0.Also I have test the data of Chr01 in a new different folder.However, the error is still shown in the figure below.

![image](https://user-images.githubusercontent.com/121594085/211882977-ff9a3ad9-0b24-49fd-b9af-3bfd38868064.png)

**Comment by bvaldebenitom** [comment]
Thanks for sharing this!

Can you test the attached developmental version? I have successfully run it twice with the files you sent me. There was an odd behavior in one of the conditions of the script, but now it is ok.

[SoloTE_pipeline_20230110.tar.gz](https://github.com/bvaldebenitom/SoloTE/files/10395996/SoloTE_pipeline_20230110.tar.gz)
