### ISSUE TITLE
SoloTE 1.04 and cellRanger bam file

### ISSUE THREAD

**Issue by IStevant** [bvaldebenitom/SoloTE#9]
Hi! 

I am trying to run SoloTE on bam files generated with CellRanger v2.1.
I noticed that the script is not identifying the bam as generated by cellRanger but STAR and thus fails the following tests.
Indeed, the command line catched by `(list(filter(lambda x:'@CO' in x,headerlines)))` is containing `STAR` although generated by cellRanger.

I had to modify by hand the SoloTE_pipeline.py script to skip the test (line 90) so the pipeline can run on my bam file. 

The bam file I am testing comes from GEO: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5595988

**Comment by bvaldebenitom** [comment]
We really appreciate the input on this issue. 

Upon modifying the script, did it run successfully? We have a developmental version that solves this issue, which we tested on several CellRanger BAM files, along the one from the link you posted.

**Comment by IStevant** [comment]
Sorry for the late reply.
No, it did not work at the end, here my log file:
```
[bam_sort_core] merging from 456 files and 12 in-memory blocks...
SoloTE started at 10:21:16
samtools found!
bedtools found!
['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chrX', 'chrY', 'chrM', 'GL456210.1', 'GL456211.1', 'GL456212.1', 'GL456213.1', 'GL456216.1', 'GL456219.1', 'GL456221.1', 'GL456233.1', 'GL456239.1', 'GL456350.1', 'GL456354.1', 'GL456359.1', 'GL456360.1', 'GL456366.1', 'GL456367.1', 'GL456368.1', 'GL456370.1', 'GL456372.1', 'GL456378.1', 'GL456379.1', 'GL456381.1', 'GL456382.1', 'GL456383.1', 'GL456385.1', 'GL456387.1', 'GL456389.1', 'GL456390.1', 'GL456392.1', 'GL456393.1', 'GL456394.1', 'GL456396.1', 'JH584292.1', 'JH584293.1', 'JH584294.1', 'JH584295.1', 'JH584296.1', 'JH584297.1', 'JH584298.1', 'JH584299.1', 'JH584300.1', 'JH584301.1', 'JH584302.1', 'JH584303.1', 'JH584304.1', 'KQ030490.1', 'KB469738.3', 'JH792830.1', 'KV575237.1', 'KK082442.1', 'KV575240.1', 'KV575235.1', 'KV575239.1', 'KQ030495.1', 'KV575238.1', 'KV575234.1', 'KQ030485.1', 'KQ030486.1', 'KQ030487.1', 'KB469739.1', 'KB469741.2', 'JH792829.1', 'KV575236.1', 'KV575233.1', 'JH792826.1', 'JH792828.1', 'KB469740.1', 'JH792832.1', 'JH792833.1', 'JH792827.1', 'JH792834.1', 'JH792831.1', 'KB469742.1', 'KQ030484.1', 'KQ030494.1', 'KQ030496.1', 'KQ030497.1', 'KQ030492.1', 'KQ030493.1', 'KQ030491.1', 'KQ030488.1', 'KQ030489.1', 'KV575232.1', 'KV575241.1', 'KV575242.1', 'KK082441.1', 'chrZ']
['@CO\tuser command line: STAR ', 'genomeDir /data/unige/funpopgen/cmayere/References/GRCm38/star ', 'readFilesIn /home/cmayere/home-chloe/Run_180215_4FC/runs_1802_170724_O_E12/SC_RNA_COUNTER_CS/SC_RNA_COUNTER/_BASIC_SC_RNA_COUNTER/EXTRACT_READS/fork0/chnk000-ub2799bbac0/files/reads.fastq/1.fastq.lz4  ', 'outSAMmultNmax -1 ', 'runThreadN 4 ', 'readNameSeparator space ', 'outSAMunmapped Within ', 'outSAMtype SAM ', 'outStd SAM ', 'outSAMorder PairedKeepInputOrder ', 'outSAMattrRGline ID:runs_1802_170724_O_E12:MissingLibrary:1:HNV23BBXX:1 SM:runs_1802_170724_O_E12 LB:MissingLibrary.1 PU:runs_1802_170724_O_E12:MissingLibrary:1:HNV23BBXX:1 PL:ILLUMINA ', 'readFilesCommand "lz4 -c -d"']
BAM file generated using CellRanger
test/test_out_SoloTE_output
test/test_out_SoloTE_temp
test
test_out
samtools view --threads 12 -d GN -U test_out_nogenes_oldtag.bam -O BAM -o temp.bam /work/istevant/data/scRNA/Nef/170724_O_XX_E12.bam.1
samtools view -d GN:- -o test_out_nogenes_newtag.bam -U test_out_genes.bam -O BAM temp.bam
samtools cat --threads 12 -o test_out_nogenes.bam test_out_nogenes_oldtag.bam test_out_nogenes_newtag.bam
samtools view --threads 12 -O BAM -o test_out_nogenes_overlappingtes.bam -L /home/istevant/work/data/scRNA/Nef/mm10_all.bed test_out_nogenes.bam
samtools index test_out_nogenes_overlappingtes.bam
bedtools bamtobed -i test_out_nogenes_overlappingtes.bam -split > test_out_nogenes_overlappingtes.bed
bedtools intersect -a /home/istevant/work/data/scRNA/Nef/mm10_all.bed -b test_out_nogenes_overlappingtes.bed -u > test_out_selectedtes.bed
python /home/istevant/tools/SoloTE_1.02/annotateBAM.py test_out_nogenes_overlappingtes.bam test_out_selectedtes.bed test_out_teannotated.bam
samtools cat --threads 12 -o test_out_full.bam test_out_genes.bam test_out_teannotated.bam
samtools sort --threads 12 -O BAM -o test_out_full_sorted.bam test_out_full.bam
samtools view -U test_out_final.bam --tag CB:- -@ 8 test_out_full_sorted.bam > /dev/null
samtools index test_out_final.bam
Process: 8065
[...]
Process: 8064
grep: test_out_allcounts.txt: No such file or directory
grep: test_out_allcounts.txt: No such file or directory
grep: test_out_allcounts.txt: No such file or directory

*****
***** ERROR: Requested column 3, but database file - only has fields 1 - 0.

*****
***** ERROR: Requested column 3, but database file - only has fields 1 - 0.

*****
***** ERROR: Requested column 3, but database file - only has fields 1 - 0.
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
Calls: read.delim -> read.table
Execution halted
[]
Creating final results directory
test/test_out_SoloTE_output was created
Traceback (most recent call last):
  File "/home/istevant/tools/SoloTE_1.02/SoloTE_pipeline.py", line 293, in <module>
    file_table = pd.read_table(input_te_file,header=None,sep="\t")
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1289, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/istevant/work/miniconda3/envs/soloTE/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by bvaldebenitom** [comment]
Can you share the output of `ls -lht` on the temp folder, and the first lines of the BED file you are using?

I run the updated pipeline with one of the BAM files available at GEO, and it finished successfully.

**Comment by bvaldebenitom** [comment]
Can you share the output of `ls -lht` on the temp folder, and the first lines of the BED file you are using?

I ran the updated pipeline with one of the BAM files available at GEO, and it finished successfully.

**Comment by Citugulia40** [comment]
Hi,
Thanks for the SoloTE. I am also receiving the error when I am using the cell ranger bam file.

"**Traceback (most recent call last):
  File "/data2/ccitu/software/SoloTE/SoloTE_1.02/SoloTE_pipeline.py", line 48, in <module>
    headerlines = pysam.view("-H",inputfile).split("\n")
  File "/data2/ccitu/software/SoloTE/SoloTE_1.02/env/lib/python3.9/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[main_samview] fail to read the header from "/tmp/tmpknvrja7s".\n**'"

Please help in resolving this error.

Thanks

**Comment by bvaldebenitom** [comment]
@Citugulia40 can you try the latest 1.05 version [available here](https://github.com/bvaldebenitom/SoloTE/releases/tag/1.05)?

**Comment by Citugulia40** [comment]
Hi, I have installed the new version but still getting error

Traceback (most recent call last):
  File "/data2/ccitu/software/SoloTE/SoloTE_pipeline.py", line 233, in <module>
    for chromosome_info in pysam.idxstats(final_bam).split("\n"):
  File "/data2/ccitu/software/SoloTE/solote/lib/python3.9/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools idxstats: failed to open "rte_final.bam": No such file or directory\n'

**Comment by bvaldebenitom** [comment]
@Citugulia40 could you share the first lines of the output of `samtools view` on the BAM file you are using?

**Comment by Citugulia40** [comment]
The samtools view of my bam file:

"**NS500496:485:HL2YFBGX3:1:13107:17093:13211	16	chr1	10547	3	3S65M30S	*	0	0	GACTCTGTGCAGAGGAGAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCCCCATGTACTCTGCGTTGATACCACTGCTT	EEEEEEE/AEEEEEEEEEEEEEEEEAEEEEEEEEEAEEEEE/EEEEEAE/EEAAE</EEEEEEEAEEEEEEE/E/EEEEEEEEEAEE/AEEEEAAAA6	NH:i:2	HI:i:1	AS:i:61	nM:i:1	ts:i:30	RG:Z:D17-8753_S1:0:1:HL2YFBGX3:1	RE:A:I	xf:i:0	CR:Z:CAAGAAAGTTCAGACT	CY:Z:AAAAAEEEEEEEEEEE	UR:Z:TGCAATTGCG	UY:Z:EEEEEEEEEE	UB:Z:TGCAATTGCG	CB:Z:D17-8753_S1_CAAGAAAGTTCAGACT-1
NS500496:485:HL2YFBGX3:3:22601:7888:4532	16	chr1	11922	1	98M	*	0	0	TGCTGTATCTTAGCCGAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTGATGCTGTGGTCTTCATCTGCAGGTGTCTGACT	EEAA<////<<A/A//EAAAAEEA/EEEE/EE/EE/EE/A</E/<AAAEE<AAA//AA/6///6EA<<//<E//<E/<//<//<A/EEEEAEEAA6AA	NH:i:4	HI:i:1	AS:i:92	nM:i:2	RG:Z:D17-8753_S1:0:1:HL2YFBGX3:3	RE:A:I	xf:i:0	CR:Z:GAATAAGCAGGGAGAG	CY:Z:AAAAAEEAEEEEEEEE	UR:Z:ATGCTATTCG	UY:Z:EEEEEEEEEE	UB:Z:ATGCTATTCG	CB:Z:D17-8753_S1_GAATAAGCAGGGAGAG-1
NS500496:485:HL2YFBGX3:4:12509:21514:14223	16	chr1	11979	1	98M	*	0	0	AGGGTCTTGATGCTGTGGTCTTCATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCC	EEEE/EEEEEAAAEEEEEEEAEAA<AAEEEEEEEAEEEEEEEEAEEAEA/EEE/EEEEEEEEAAEEEE/EEEEEEEEEEEEEEEEEE/EEEE//AAAA	NH:i:3	HI:i:1	AS:i:96	nM:i:0	RG:Z:D17-8753_S1:0:1:HL2YFBGX3:4	RE:A:I	xf:i:0	CR:Z:GAATAAGCAGGGAGAG	CY:Z:AAAAAEEEEEEEEEEE	UR:Z:ATGCTATTCG	UY:Z:EEEEEEEEEE	UB:Z:ATGCTATTCG	CB:Z:D17-8753_S1_GAATAAGCAGGGAGAG-1
NS500496:485:HL2YFBGX3:3:21401:11730:19559	0	chr1	14044	0	94M4S	*	0	0	GTGCCAGTTCCTCCAAGACGATGGCACCTCCCTCCCTCTCAACCACTTGAGCAATCGCCAAGACATGTTCTGACAAAACAGAAGCAATTGTGCCCATG	A/AAAEEE//</AEE///E6/E/EEAE/EEE////6A</E///A<E//AEE////E//A//E/AEA/EE/<///<//E/A//<////EEE</E////<	NH:i:6	HI:i:1	AS:i:72	nM:i:10	RG:Z:D17-8753_S1:0:1:HL2YFBGX3:3	RE:A:I	xf:i:0	CR:Z:ACGGCCAAGCACACAG	CY:Z:AAAAAEAEEEAEEEEA	UR:Z:TATGCTCCCA	UY:Z:EEEEE/A/EE	UB:Z:TATGCTCCCA	CB:Z:D17-8753_S1_ACGGCCAAGCACACAG-1**"

**Comment by bvaldebenitom** [comment]
@Citugulia40 ok, looks like there is a match on the chromosome identifiers, which may have been an issue.

Can you share the command you used to run the pipeline? Also, please share the contents of the `solote_rte` directory located inside `rte_SoloTE_temp/` and the contents of the directory one level up of `rte_SoloTE_temp`

**Comment by Citugulia40** [comment]
ls rte_SoloTE_temp
rte_nogenes_overlappingtes.bed       rte_selectedtes.bed

SoloTE command
"python SoloTE_pipeline.py --threads 64 --bam /data2/ccitu/rte_project/src/data/dataset1/cell_count/D17-8753_S1/outs/out.bam --teannotation /data2/ccitu/rte_project/src/data/dataset1/solote/solote_bed_file_final.txt --outputprefix rte --outputdir solote"

**Comment by Citugulia40** [comment]
Hi, 
Have you got any solution for my error?

Thanks

**Comment by bvaldebenitom** [comment]
Hi @Citugulia40,

can you test the developmental version shared in this [post](https://github.com/bvaldebenitom/SoloTE/issues/8#issuecomment-1432021287)?

That's the latest developmental version, which seem to have fixed most of the issues reported.

**Comment by Citugulia40** [comment]
Hi,
I have installed the developmental version that you have mentioned and getting the same error.

PFA my log file.
[rte.log](https://github.com/bvaldebenitom/SoloTE/files/10786700/rte.log)



Thanks

**Comment by bvaldebenitom** [comment]
@Citugulia40 can you share the output of `samtools --version`?

**Comment by Citugulia40** [comment]
Hi,
It got resolved after changing the samtools versions.

Thank you so much for your help.

**Comment by vinothkr11** [comment]
I am having a similar issue with version SoloTE 1.10. 
This is the input
`python SoloTE_pipeline.py --threads 320 --bam /scratch/j/jczplab/vrajan11/lineage-2024/GEX-BAM/d3r1b1.bam --teannotation hg38_rmsk.bed --outputprefix d3r1b1 --outputdir d3r1b1`

This is the error message I get
samtools sort -@ 320 -O BAM -o d3r1b1_teannotated.bam temp_annotated_te.bam
samtools merge --threads 320 -o - /scratch/j/jczplab/vrajan11/lineage-2024/GEX-BAM/d3r1b1.bam d3r1b1_teannotated.bam|samtools view -@ 320 -O BAM -o d3r1b1_final.bam -e 'exists([CB]) && exists([UB]) && exists([GN]) && [CB]!="-" && [UB]!="-" && [GN]!="-"' --keep-tag GN,CB,UB
samtools index d3r1b1_final.bam
Traceback (most recent call last):
  File "/gpfs/fs0/scratch/j/jczplab/vrajan11/TE_10_24/SoloTE_pipeline.py", line 187, in <module>
    for chromosome_info in pysam.idxstats(final_bam).split("\n"):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/fs0/scratch/j/jczplab/vrajan11/cospar_kernel/lib/python3.11/site-packages/pysam/utils.py", line 83, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools idxstats: failed to open "d3r1b1_final.bam": No such file or directory\n'

The following are the versions of samtools and bedtools: samtools/1.20 and bedtools/2.31.0. I have tried samtools/1.16.1 and an earlier version of bedtools, which produced the same output. Please help
